namespace Jetpac2.Core

/// The CE instruction vocabulary (generated by tools/gen_z80table.py). Every
/// named op carries its assembled encoding and dispatches its Run to the
/// validated Z80Table slot, so each op is track-perfect by construction and
/// the per-op oracle test (--test z80ops) proves it. Memory operands use the
/// PTR suffix ((HL), (nn)); (IX+d)/(IY+d) use IXd/IYd; BIT/RES/SET bake the
/// bit number into the name (BIT0_B ... SET7_PTR_IYd).
module Z80Vocab =

  open Z80
  let LD_B_B =
    mkOp "LD B,B" [| 0x40uy |] (runOf Z80Table.main 0x40)
  let LD_B_C =
    mkOp "LD B,C" [| 0x41uy |] (runOf Z80Table.main 0x41)
  let LD_B_D =
    mkOp "LD B,D" [| 0x42uy |] (runOf Z80Table.main 0x42)
  let LD_B_E =
    mkOp "LD B,E" [| 0x43uy |] (runOf Z80Table.main 0x43)
  let LD_B_H =
    mkOp "LD B,H" [| 0x44uy |] (runOf Z80Table.main 0x44)
  let LD_B_L =
    mkOp "LD B,L" [| 0x45uy |] (runOf Z80Table.main 0x45)
  let LD_B_A =
    mkOp "LD B,A" [| 0x47uy |] (runOf Z80Table.main 0x47)
  let LD_C_B =
    mkOp "LD C,B" [| 0x48uy |] (runOf Z80Table.main 0x48)
  let LD_C_C =
    mkOp "LD C,C" [| 0x49uy |] (runOf Z80Table.main 0x49)
  let LD_C_D =
    mkOp "LD C,D" [| 0x4auy |] (runOf Z80Table.main 0x4A)
  let LD_C_E =
    mkOp "LD C,E" [| 0x4buy |] (runOf Z80Table.main 0x4B)
  let LD_C_H =
    mkOp "LD C,H" [| 0x4cuy |] (runOf Z80Table.main 0x4C)
  let LD_C_L =
    mkOp "LD C,L" [| 0x4duy |] (runOf Z80Table.main 0x4D)
  let LD_C_A =
    mkOp "LD C,A" [| 0x4fuy |] (runOf Z80Table.main 0x4F)
  let LD_D_B =
    mkOp "LD D,B" [| 0x50uy |] (runOf Z80Table.main 0x50)
  let LD_D_C =
    mkOp "LD D,C" [| 0x51uy |] (runOf Z80Table.main 0x51)
  let LD_D_D =
    mkOp "LD D,D" [| 0x52uy |] (runOf Z80Table.main 0x52)
  let LD_D_E =
    mkOp "LD D,E" [| 0x53uy |] (runOf Z80Table.main 0x53)
  let LD_D_H =
    mkOp "LD D,H" [| 0x54uy |] (runOf Z80Table.main 0x54)
  let LD_D_L =
    mkOp "LD D,L" [| 0x55uy |] (runOf Z80Table.main 0x55)
  let LD_D_A =
    mkOp "LD D,A" [| 0x57uy |] (runOf Z80Table.main 0x57)
  let LD_E_B =
    mkOp "LD E,B" [| 0x58uy |] (runOf Z80Table.main 0x58)
  let LD_E_C =
    mkOp "LD E,C" [| 0x59uy |] (runOf Z80Table.main 0x59)
  let LD_E_D =
    mkOp "LD E,D" [| 0x5auy |] (runOf Z80Table.main 0x5A)
  let LD_E_E =
    mkOp "LD E,E" [| 0x5buy |] (runOf Z80Table.main 0x5B)
  let LD_E_H =
    mkOp "LD E,H" [| 0x5cuy |] (runOf Z80Table.main 0x5C)
  let LD_E_L =
    mkOp "LD E,L" [| 0x5duy |] (runOf Z80Table.main 0x5D)
  let LD_E_A =
    mkOp "LD E,A" [| 0x5fuy |] (runOf Z80Table.main 0x5F)
  let LD_H_B =
    mkOp "LD H,B" [| 0x60uy |] (runOf Z80Table.main 0x60)
  let LD_H_C =
    mkOp "LD H,C" [| 0x61uy |] (runOf Z80Table.main 0x61)
  let LD_H_D =
    mkOp "LD H,D" [| 0x62uy |] (runOf Z80Table.main 0x62)
  let LD_H_E =
    mkOp "LD H,E" [| 0x63uy |] (runOf Z80Table.main 0x63)
  let LD_H_H =
    mkOp "LD H,H" [| 0x64uy |] (runOf Z80Table.main 0x64)
  let LD_H_L =
    mkOp "LD H,L" [| 0x65uy |] (runOf Z80Table.main 0x65)
  let LD_H_A =
    mkOp "LD H,A" [| 0x67uy |] (runOf Z80Table.main 0x67)
  let LD_L_B =
    mkOp "LD L,B" [| 0x68uy |] (runOf Z80Table.main 0x68)
  let LD_L_C =
    mkOp "LD L,C" [| 0x69uy |] (runOf Z80Table.main 0x69)
  let LD_L_D =
    mkOp "LD L,D" [| 0x6auy |] (runOf Z80Table.main 0x6A)
  let LD_L_E =
    mkOp "LD L,E" [| 0x6buy |] (runOf Z80Table.main 0x6B)
  let LD_L_H =
    mkOp "LD L,H" [| 0x6cuy |] (runOf Z80Table.main 0x6C)
  let LD_L_L =
    mkOp "LD L,L" [| 0x6duy |] (runOf Z80Table.main 0x6D)
  let LD_L_A =
    mkOp "LD L,A" [| 0x6fuy |] (runOf Z80Table.main 0x6F)
  let LD_A_B =
    mkOp "LD A,B" [| 0x78uy |] (runOf Z80Table.main 0x78)
  let LD_A_C =
    mkOp "LD A,C" [| 0x79uy |] (runOf Z80Table.main 0x79)
  let LD_A_D =
    mkOp "LD A,D" [| 0x7auy |] (runOf Z80Table.main 0x7A)
  let LD_A_E =
    mkOp "LD A,E" [| 0x7buy |] (runOf Z80Table.main 0x7B)
  let LD_A_H =
    mkOp "LD A,H" [| 0x7cuy |] (runOf Z80Table.main 0x7C)
  let LD_A_L =
    mkOp "LD A,L" [| 0x7duy |] (runOf Z80Table.main 0x7D)
  let LD_A_A =
    mkOp "LD A,A" [| 0x7fuy |] (runOf Z80Table.main 0x7F)
  let LD_B_PTR_HL =
    mkOp "LD B,(HL)" [| 0x46uy |] (runOf Z80Table.main 0x46)
  let LD_C_PTR_HL =
    mkOp "LD C,(HL)" [| 0x4euy |] (runOf Z80Table.main 0x4E)
  let LD_D_PTR_HL =
    mkOp "LD D,(HL)" [| 0x56uy |] (runOf Z80Table.main 0x56)
  let LD_E_PTR_HL =
    mkOp "LD E,(HL)" [| 0x5euy |] (runOf Z80Table.main 0x5E)
  let LD_H_PTR_HL =
    mkOp "LD H,(HL)" [| 0x66uy |] (runOf Z80Table.main 0x66)
  let LD_L_PTR_HL =
    mkOp "LD L,(HL)" [| 0x6euy |] (runOf Z80Table.main 0x6E)
  let LD_A_PTR_HL =
    mkOp "LD A,(HL)" [| 0x7euy |] (runOf Z80Table.main 0x7E)
  let LD_PTR_HL_B =
    mkOp "LD (HL),B" [| 0x70uy |] (runOf Z80Table.main 0x70)
  let LD_PTR_HL_C =
    mkOp "LD (HL),C" [| 0x71uy |] (runOf Z80Table.main 0x71)
  let LD_PTR_HL_D =
    mkOp "LD (HL),D" [| 0x72uy |] (runOf Z80Table.main 0x72)
  let LD_PTR_HL_E =
    mkOp "LD (HL),E" [| 0x73uy |] (runOf Z80Table.main 0x73)
  let LD_PTR_HL_H =
    mkOp "LD (HL),H" [| 0x74uy |] (runOf Z80Table.main 0x74)
  let LD_PTR_HL_L =
    mkOp "LD (HL),L" [| 0x75uy |] (runOf Z80Table.main 0x75)
  let LD_PTR_HL_A =
    mkOp "LD (HL),A" [| 0x77uy |] (runOf Z80Table.main 0x77)
  let LD_B (n : int) =
    mkOp "LD B,n" [| 0x06uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0x06)
  let LD_C (n : int) =
    mkOp "LD C,n" [| 0x0euy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0x0E)
  let LD_D (n : int) =
    mkOp "LD D,n" [| 0x16uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0x16)
  let LD_E (n : int) =
    mkOp "LD E,n" [| 0x1euy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0x1E)
  let LD_H (n : int) =
    mkOp "LD H,n" [| 0x26uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0x26)
  let LD_L (n : int) =
    mkOp "LD L,n" [| 0x2euy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0x2E)
  let LD_A (n : int) =
    mkOp "LD A,n" [| 0x3euy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0x3E)
  let LD_A_ptr (nn : int) =
    mkOp "LD A,(nn)" [| 0x3auy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x3A)
  let LD_ptr_A (nn : int) =
    mkOp "LD (nn),A" [| 0x32uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x32)
  let LD_A_BC =
    mkOp "LD A,(BC)" [| 0x0Auy |] (runOf Z80Table.main 0x0A)
  let LD_A_DE =
    mkOp "LD A,(DE)" [| 0x1Auy |] (runOf Z80Table.main 0x1A)
  let LD_BC_A =
    mkOp "LD (BC),A" [| 0x02uy |] (runOf Z80Table.main 0x02)
  let LD_DE_A =
    mkOp "LD (DE),A" [| 0x12uy |] (runOf Z80Table.main 0x12)
  let LD_BC (imm : int) =
    mkOp "LD BC,nn" [| 0x01uy; byte (imm &&& 0xFF); byte ((imm >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x01)
  let LD_DE (imm : int) =
    mkOp "LD DE,nn" [| 0x11uy; byte (imm &&& 0xFF); byte ((imm >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x11)
  let LD_HL (imm : int) =
    mkOp "LD HL,nn" [| 0x21uy; byte (imm &&& 0xFF); byte ((imm >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x21)
  let LD_SP (imm : int) =
    mkOp "LD SP,nn" [| 0x31uy; byte (imm &&& 0xFF); byte ((imm >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x31)
  let LD_IX (imm : int) =
    mkOp "LD IX,nn" [| 0xdduy; 0x21uy; byte (imm &&& 0xFF); byte ((imm >>> 8) &&& 0xFF) |] (runOf Z80Table.dd 0x21)
  let LD_IY (imm : int) =
    mkOp "LD IY,nn" [| 0xfduy; 0x21uy; byte (imm &&& 0xFF); byte ((imm >>> 8) &&& 0xFF) |] (runOf Z80Table.fd 0x21)
  let LD_HL_ptr (nn : int) =
    mkOp "LD HL,(nn)" [| 0x2auy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x2A)
  let LD_ptr_HL (nn : int) =
    mkOp "LD (nn),HL" [| 0x22uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0x22)
  let LD_IX_ptr (nn : int) =
    mkOp "LD IX,(nn)" [| 0xdduy; 0x2auy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.dd 0x2A)
  let LD_ptr_IX (nn : int) =
    mkOp "LD (nn),IX" [| 0xdduy; 0x22uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.dd 0x22)
  let LD_IY_ptr (nn : int) =
    mkOp "LD IY,(nn)" [| 0xfduy; 0x2auy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.fd 0x2A)
  let LD_ptr_IY (nn : int) =
    mkOp "LD (nn),IY" [| 0xfduy; 0x22uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.fd 0x22)
  let LD_ptr_BC (nn : int) =
    mkOp "LD (nn),BC" [| 0xeduy; 0x43uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.ed 0x43)
  let LD_BC_ptr (nn : int) =
    mkOp "LD BC,(nn)" [| 0xeduy; 0x4buy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.ed 0x4B)
  let LD_ptr_DE (nn : int) =
    mkOp "LD (nn),DE" [| 0xeduy; 0x53uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.ed 0x53)
  let LD_DE_ptr (nn : int) =
    mkOp "LD DE,(nn)" [| 0xeduy; 0x5buy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.ed 0x5B)
  let LD_ptr_SP (nn : int) =
    mkOp "LD (nn),SP" [| 0xeduy; 0x73uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.ed 0x73)
  let LD_SP_ptr (nn : int) =
    mkOp "LD SP,(nn)" [| 0xeduy; 0x7buy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.ed 0x7B)
  let LD_SP_HL =
    mkOp "LD SP,HL" [| 0xF9uy |] (runOf Z80Table.main 0xF9)
  let LD_SP_IX =
    mkOp "LD SP,IX" [| 0xDDuy; 0xF9uy |] (runOf Z80Table.dd 0xF9)
  let LD_SP_IY =
    mkOp "LD SP,IY" [| 0xFDuy; 0xF9uy |] (runOf Z80Table.fd 0xF9)
  let LD_A_I =
    mkOp "LD A,I" [| 0xEDuy; 0x57uy |] (runOf Z80Table.ed 0x57)
  let LD_A_R =
    mkOp "LD A,R" [| 0xEDuy; 0x5Fuy |] (runOf Z80Table.ed 0x5F)
  let LD_I_A =
    mkOp "LD I,A" [| 0xEDuy; 0x47uy |] (runOf Z80Table.ed 0x47)
  let LD_R_A =
    mkOp "LD R,A" [| 0xEDuy; 0x4Fuy |] (runOf Z80Table.ed 0x4F)
  let LD_B_IXH =
    mkOp "LD B,IXH" [| 0xDDuy; 0x44uy |] (runOf Z80Table.dd 0x44)
  let LD_B_IXL =
    mkOp "LD B,IXL" [| 0xDDuy; 0x45uy |] (runOf Z80Table.dd 0x45)
  let LD_C_IXH =
    mkOp "LD C,IXH" [| 0xDDuy; 0x4cuy |] (runOf Z80Table.dd 0x4C)
  let LD_C_IXL =
    mkOp "LD C,IXL" [| 0xDDuy; 0x4duy |] (runOf Z80Table.dd 0x4D)
  let LD_D_IXH =
    mkOp "LD D,IXH" [| 0xDDuy; 0x54uy |] (runOf Z80Table.dd 0x54)
  let LD_D_IXL =
    mkOp "LD D,IXL" [| 0xDDuy; 0x55uy |] (runOf Z80Table.dd 0x55)
  let LD_E_IXH =
    mkOp "LD E,IXH" [| 0xDDuy; 0x5cuy |] (runOf Z80Table.dd 0x5C)
  let LD_E_IXL =
    mkOp "LD E,IXL" [| 0xDDuy; 0x5duy |] (runOf Z80Table.dd 0x5D)
  let LD_IXH_B =
    mkOp "LD IXH,B" [| 0xDDuy; 0x60uy |] (runOf Z80Table.dd 0x60)
  let LD_IXH_C =
    mkOp "LD IXH,C" [| 0xDDuy; 0x61uy |] (runOf Z80Table.dd 0x61)
  let LD_IXH_D =
    mkOp "LD IXH,D" [| 0xDDuy; 0x62uy |] (runOf Z80Table.dd 0x62)
  let LD_IXH_E =
    mkOp "LD IXH,E" [| 0xDDuy; 0x63uy |] (runOf Z80Table.dd 0x63)
  let LD_IXH_A =
    mkOp "LD IXH,A" [| 0xDDuy; 0x67uy |] (runOf Z80Table.dd 0x67)
  let LD_IXL_B =
    mkOp "LD IXL,B" [| 0xDDuy; 0x68uy |] (runOf Z80Table.dd 0x68)
  let LD_IXL_C =
    mkOp "LD IXL,C" [| 0xDDuy; 0x69uy |] (runOf Z80Table.dd 0x69)
  let LD_IXL_D =
    mkOp "LD IXL,D" [| 0xDDuy; 0x6auy |] (runOf Z80Table.dd 0x6A)
  let LD_IXL_E =
    mkOp "LD IXL,E" [| 0xDDuy; 0x6buy |] (runOf Z80Table.dd 0x6B)
  let LD_IXL_A =
    mkOp "LD IXL,A" [| 0xDDuy; 0x6fuy |] (runOf Z80Table.dd 0x6F)
  let LD_IXH_n (n : int) =
    mkOp "LD IXH,n" [| 0xdduy; 0x26uy; byte (n &&& 0xFF) |] (runOf Z80Table.dd 0x26)
  let LD_IXL_n (n : int) =
    mkOp "LD IXL,n" [| 0xdduy; 0x2euy; byte (n &&& 0xFF) |] (runOf Z80Table.dd 0x2E)
  let LD_B_IXd (d : int) =
    mkOp "LD B,(IX+d)" [| 0xdduy; 0x46uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x46)
  let LD_C_IXd (d : int) =
    mkOp "LD C,(IX+d)" [| 0xdduy; 0x4euy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x4E)
  let LD_D_IXd (d : int) =
    mkOp "LD D,(IX+d)" [| 0xdduy; 0x56uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x56)
  let LD_E_IXd (d : int) =
    mkOp "LD E,(IX+d)" [| 0xdduy; 0x5euy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x5E)
  let LD_H_IXd (d : int) =
    mkOp "LD H,(IX+d)" [| 0xdduy; 0x66uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x66)
  let LD_L_IXd (d : int) =
    mkOp "LD L,(IX+d)" [| 0xdduy; 0x6euy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x6E)
  let LD_A_IXd (d : int) =
    mkOp "LD A,(IX+d)" [| 0xdduy; 0x7euy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x7E)
  let LD_B_IYd (d : int) =
    mkOp "LD B,(IY+d)" [| 0xfduy; 0x46uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x46)
  let LD_C_IYd (d : int) =
    mkOp "LD C,(IY+d)" [| 0xfduy; 0x4euy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x4E)
  let LD_D_IYd (d : int) =
    mkOp "LD D,(IY+d)" [| 0xfduy; 0x56uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x56)
  let LD_E_IYd (d : int) =
    mkOp "LD E,(IY+d)" [| 0xfduy; 0x5euy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x5E)
  let LD_H_IYd (d : int) =
    mkOp "LD H,(IY+d)" [| 0xfduy; 0x66uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x66)
  let LD_L_IYd (d : int) =
    mkOp "LD L,(IY+d)" [| 0xfduy; 0x6euy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x6E)
  let LD_A_IYd (d : int) =
    mkOp "LD A,(IY+d)" [| 0xfduy; 0x7euy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x7E)
  let LD_IXd_B (d : int) =
    mkOp "LD (IX+d),B" [| 0xdduy; 0x70uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x70)
  let LD_IXd_C (d : int) =
    mkOp "LD (IX+d),C" [| 0xdduy; 0x71uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x71)
  let LD_IXd_D (d : int) =
    mkOp "LD (IX+d),D" [| 0xdduy; 0x72uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x72)
  let LD_IXd_E (d : int) =
    mkOp "LD (IX+d),E" [| 0xdduy; 0x73uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x73)
  let LD_IXd_H (d : int) =
    mkOp "LD (IX+d),H" [| 0xdduy; 0x74uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x74)
  let LD_IXd_L (d : int) =
    mkOp "LD (IX+d),L" [| 0xdduy; 0x75uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x75)
  let LD_IXd_A (d : int) =
    mkOp "LD (IX+d),A" [| 0xdduy; 0x77uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x77)
  let LD_IYd_B (d : int) =
    mkOp "LD (IY+d),B" [| 0xfduy; 0x70uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x70)
  let LD_IYd_C (d : int) =
    mkOp "LD (IY+d),C" [| 0xfduy; 0x71uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x71)
  let LD_IYd_D (d : int) =
    mkOp "LD (IY+d),D" [| 0xfduy; 0x72uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x72)
  let LD_IYd_E (d : int) =
    mkOp "LD (IY+d),E" [| 0xfduy; 0x73uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x73)
  let LD_IYd_H (d : int) =
    mkOp "LD (IY+d),H" [| 0xfduy; 0x74uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x74)
  let LD_IYd_L (d : int) =
    mkOp "LD (IY+d),L" [| 0xfduy; 0x75uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x75)
  let LD_IYd_A (d : int) =
    mkOp "LD (IY+d),A" [| 0xfduy; 0x77uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x77)
  let ADD_A_B =
    mkOp "ADD A,B" [| 0x80uy |] (runOf Z80Table.main 0x80)
  let ADD_A_C =
    mkOp "ADD A,C" [| 0x81uy |] (runOf Z80Table.main 0x81)
  let ADD_A_D =
    mkOp "ADD A,D" [| 0x82uy |] (runOf Z80Table.main 0x82)
  let ADD_A_E =
    mkOp "ADD A,E" [| 0x83uy |] (runOf Z80Table.main 0x83)
  let ADD_A_H =
    mkOp "ADD A,H" [| 0x84uy |] (runOf Z80Table.main 0x84)
  let ADD_A_L =
    mkOp "ADD A,L" [| 0x85uy |] (runOf Z80Table.main 0x85)
  let ADD_A_A =
    mkOp "ADD A,A" [| 0x87uy |] (runOf Z80Table.main 0x87)
  let ADD_A_PTR_HL =
    mkOp "ADD A,(HL)" [| 0x86uy |] (runOf Z80Table.main 0x86)
  let ADD_A_n (n : int) =
    mkOp "ADD A,n" [| 0xc6uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xC6)
  let ADD_A_IXd (d : int) =
    mkOp "ADD A,(IX+d)" [| 0xdduy; 0x86uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x86)
  let ADD_A_IYd (d : int) =
    mkOp "ADD A,(IY+d)" [| 0xfduy; 0x86uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x86)
  let ADC_A_B =
    mkOp "ADC A,B" [| 0x88uy |] (runOf Z80Table.main 0x88)
  let ADC_A_C =
    mkOp "ADC A,C" [| 0x89uy |] (runOf Z80Table.main 0x89)
  let ADC_A_D =
    mkOp "ADC A,D" [| 0x8auy |] (runOf Z80Table.main 0x8A)
  let ADC_A_E =
    mkOp "ADC A,E" [| 0x8buy |] (runOf Z80Table.main 0x8B)
  let ADC_A_H =
    mkOp "ADC A,H" [| 0x8cuy |] (runOf Z80Table.main 0x8C)
  let ADC_A_L =
    mkOp "ADC A,L" [| 0x8duy |] (runOf Z80Table.main 0x8D)
  let ADC_A_A =
    mkOp "ADC A,A" [| 0x8fuy |] (runOf Z80Table.main 0x8F)
  let ADC_A_PTR_HL =
    mkOp "ADC A,(HL)" [| 0x8euy |] (runOf Z80Table.main 0x8E)
  let ADC_A_n (n : int) =
    mkOp "ADC A,n" [| 0xceuy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xCE)
  let ADC_A_IXd (d : int) =
    mkOp "ADC A,(IX+d)" [| 0xdduy; 0x8euy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x8E)
  let ADC_A_IYd (d : int) =
    mkOp "ADC A,(IY+d)" [| 0xfduy; 0x8euy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x8E)
  let SUB_A_B =
    mkOp "SUB A,B" [| 0x90uy |] (runOf Z80Table.main 0x90)
  let SUB_A_C =
    mkOp "SUB A,C" [| 0x91uy |] (runOf Z80Table.main 0x91)
  let SUB_A_D =
    mkOp "SUB A,D" [| 0x92uy |] (runOf Z80Table.main 0x92)
  let SUB_A_E =
    mkOp "SUB A,E" [| 0x93uy |] (runOf Z80Table.main 0x93)
  let SUB_A_H =
    mkOp "SUB A,H" [| 0x94uy |] (runOf Z80Table.main 0x94)
  let SUB_A_L =
    mkOp "SUB A,L" [| 0x95uy |] (runOf Z80Table.main 0x95)
  let SUB_A_A =
    mkOp "SUB A,A" [| 0x97uy |] (runOf Z80Table.main 0x97)
  let SUB_A_PTR_HL =
    mkOp "SUB A,(HL)" [| 0x96uy |] (runOf Z80Table.main 0x96)
  let SUB_A_n (n : int) =
    mkOp "SUB A,n" [| 0xd6uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xD6)
  let SUB_A_IXd (d : int) =
    mkOp "SUB A,(IX+d)" [| 0xdduy; 0x96uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x96)
  let SUB_A_IYd (d : int) =
    mkOp "SUB A,(IY+d)" [| 0xfduy; 0x96uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x96)
  let SBC_A_B =
    mkOp "SBC A,B" [| 0x98uy |] (runOf Z80Table.main 0x98)
  let SBC_A_C =
    mkOp "SBC A,C" [| 0x99uy |] (runOf Z80Table.main 0x99)
  let SBC_A_D =
    mkOp "SBC A,D" [| 0x9auy |] (runOf Z80Table.main 0x9A)
  let SBC_A_E =
    mkOp "SBC A,E" [| 0x9buy |] (runOf Z80Table.main 0x9B)
  let SBC_A_H =
    mkOp "SBC A,H" [| 0x9cuy |] (runOf Z80Table.main 0x9C)
  let SBC_A_L =
    mkOp "SBC A,L" [| 0x9duy |] (runOf Z80Table.main 0x9D)
  let SBC_A_A =
    mkOp "SBC A,A" [| 0x9fuy |] (runOf Z80Table.main 0x9F)
  let SBC_A_PTR_HL =
    mkOp "SBC A,(HL)" [| 0x9euy |] (runOf Z80Table.main 0x9E)
  let SBC_A_n (n : int) =
    mkOp "SBC A,n" [| 0xdeuy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xDE)
  let SBC_A_IXd (d : int) =
    mkOp "SBC A,(IX+d)" [| 0xdduy; 0x9euy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x9E)
  let SBC_A_IYd (d : int) =
    mkOp "SBC A,(IY+d)" [| 0xfduy; 0x9euy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0x9E)
  let AND_A_B =
    mkOp "AND A,B" [| 0xa0uy |] (runOf Z80Table.main 0xA0)
  let AND_A_C =
    mkOp "AND A,C" [| 0xa1uy |] (runOf Z80Table.main 0xA1)
  let AND_A_D =
    mkOp "AND A,D" [| 0xa2uy |] (runOf Z80Table.main 0xA2)
  let AND_A_E =
    mkOp "AND A,E" [| 0xa3uy |] (runOf Z80Table.main 0xA3)
  let AND_A_H =
    mkOp "AND A,H" [| 0xa4uy |] (runOf Z80Table.main 0xA4)
  let AND_A_L =
    mkOp "AND A,L" [| 0xa5uy |] (runOf Z80Table.main 0xA5)
  let AND_A_A =
    mkOp "AND A,A" [| 0xa7uy |] (runOf Z80Table.main 0xA7)
  let AND_A_PTR_HL =
    mkOp "AND A,(HL)" [| 0xa6uy |] (runOf Z80Table.main 0xA6)
  let AND_A_n (n : int) =
    mkOp "AND A,n" [| 0xe6uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xE6)
  let AND_A_IXd (d : int) =
    mkOp "AND A,(IX+d)" [| 0xdduy; 0xa6uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0xA6)
  let AND_A_IYd (d : int) =
    mkOp "AND A,(IY+d)" [| 0xfduy; 0xa6uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0xA6)
  let XOR_A_B =
    mkOp "XOR A,B" [| 0xa8uy |] (runOf Z80Table.main 0xA8)
  let XOR_A_C =
    mkOp "XOR A,C" [| 0xa9uy |] (runOf Z80Table.main 0xA9)
  let XOR_A_D =
    mkOp "XOR A,D" [| 0xaauy |] (runOf Z80Table.main 0xAA)
  let XOR_A_E =
    mkOp "XOR A,E" [| 0xabuy |] (runOf Z80Table.main 0xAB)
  let XOR_A_H =
    mkOp "XOR A,H" [| 0xacuy |] (runOf Z80Table.main 0xAC)
  let XOR_A_L =
    mkOp "XOR A,L" [| 0xaduy |] (runOf Z80Table.main 0xAD)
  let XOR_A_A =
    mkOp "XOR A,A" [| 0xafuy |] (runOf Z80Table.main 0xAF)
  let XOR_A_PTR_HL =
    mkOp "XOR A,(HL)" [| 0xaeuy |] (runOf Z80Table.main 0xAE)
  let XOR_A_n (n : int) =
    mkOp "XOR A,n" [| 0xeeuy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xEE)
  let XOR_A_IXd (d : int) =
    mkOp "XOR A,(IX+d)" [| 0xdduy; 0xaeuy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0xAE)
  let XOR_A_IYd (d : int) =
    mkOp "XOR A,(IY+d)" [| 0xfduy; 0xaeuy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0xAE)
  let OR_A_B =
    mkOp "OR A,B" [| 0xb0uy |] (runOf Z80Table.main 0xB0)
  let OR_A_C =
    mkOp "OR A,C" [| 0xb1uy |] (runOf Z80Table.main 0xB1)
  let OR_A_D =
    mkOp "OR A,D" [| 0xb2uy |] (runOf Z80Table.main 0xB2)
  let OR_A_E =
    mkOp "OR A,E" [| 0xb3uy |] (runOf Z80Table.main 0xB3)
  let OR_A_H =
    mkOp "OR A,H" [| 0xb4uy |] (runOf Z80Table.main 0xB4)
  let OR_A_L =
    mkOp "OR A,L" [| 0xb5uy |] (runOf Z80Table.main 0xB5)
  let OR_A_A =
    mkOp "OR A,A" [| 0xb7uy |] (runOf Z80Table.main 0xB7)
  let OR_A_PTR_HL =
    mkOp "OR A,(HL)" [| 0xb6uy |] (runOf Z80Table.main 0xB6)
  let OR_A_n (n : int) =
    mkOp "OR A,n" [| 0xf6uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xF6)
  let OR_A_IXd (d : int) =
    mkOp "OR A,(IX+d)" [| 0xdduy; 0xb6uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0xB6)
  let OR_A_IYd (d : int) =
    mkOp "OR A,(IY+d)" [| 0xfduy; 0xb6uy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0xB6)
  let CP_A_B =
    mkOp "CP A,B" [| 0xb8uy |] (runOf Z80Table.main 0xB8)
  let CP_A_C =
    mkOp "CP A,C" [| 0xb9uy |] (runOf Z80Table.main 0xB9)
  let CP_A_D =
    mkOp "CP A,D" [| 0xbauy |] (runOf Z80Table.main 0xBA)
  let CP_A_E =
    mkOp "CP A,E" [| 0xbbuy |] (runOf Z80Table.main 0xBB)
  let CP_A_H =
    mkOp "CP A,H" [| 0xbcuy |] (runOf Z80Table.main 0xBC)
  let CP_A_L =
    mkOp "CP A,L" [| 0xbduy |] (runOf Z80Table.main 0xBD)
  let CP_A_A =
    mkOp "CP A,A" [| 0xbfuy |] (runOf Z80Table.main 0xBF)
  let CP_A_PTR_HL =
    mkOp "CP A,(HL)" [| 0xbeuy |] (runOf Z80Table.main 0xBE)
  let CP_A_n (n : int) =
    mkOp "CP A,n" [| 0xfeuy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xFE)
  let CP_A_IXd (d : int) =
    mkOp "CP A,(IX+d)" [| 0xdduy; 0xbeuy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0xBE)
  let CP_A_IYd (d : int) =
    mkOp "CP A,(IY+d)" [| 0xfduy; 0xbeuy; byte (d &&& 0xFF) |] (runOf Z80Table.fd 0xBE)
  let ADD_HL_BC =
    mkOp "ADD HL,BC" [| 0x09uy |] (runOf Z80Table.main 0x09)
  let ADC_HL_BC =
    mkOp "ADC HL,BC" [| 0xEDuy; 0x4auy |] (runOf Z80Table.ed 0x4A)
  let SBC_HL_BC =
    mkOp "SBC HL,BC" [| 0xEDuy; 0x42uy |] (runOf Z80Table.ed 0x42)
  let ADD_HL_DE =
    mkOp "ADD HL,DE" [| 0x19uy |] (runOf Z80Table.main 0x19)
  let ADC_HL_DE =
    mkOp "ADC HL,DE" [| 0xEDuy; 0x5auy |] (runOf Z80Table.ed 0x5A)
  let SBC_HL_DE =
    mkOp "SBC HL,DE" [| 0xEDuy; 0x52uy |] (runOf Z80Table.ed 0x52)
  let ADD_HL_HL =
    mkOp "ADD HL,HL" [| 0x29uy |] (runOf Z80Table.main 0x29)
  let ADC_HL_HL =
    mkOp "ADC HL,HL" [| 0xEDuy; 0x6auy |] (runOf Z80Table.ed 0x6A)
  let SBC_HL_HL =
    mkOp "SBC HL,HL" [| 0xEDuy; 0x62uy |] (runOf Z80Table.ed 0x62)
  let ADD_HL_SP =
    mkOp "ADD HL,SP" [| 0x39uy |] (runOf Z80Table.main 0x39)
  let ADC_HL_SP =
    mkOp "ADC HL,SP" [| 0xEDuy; 0x7auy |] (runOf Z80Table.ed 0x7A)
  let SBC_HL_SP =
    mkOp "SBC HL,SP" [| 0xEDuy; 0x72uy |] (runOf Z80Table.ed 0x72)
  let ADD_IX_BC =
    mkOp "ADD IX,BC" [| 0xDDuy; 0x09uy |] (runOf Z80Table.dd 0x09)
  let ADD_IY_BC =
    mkOp "ADD IY,BC" [| 0xFDuy; 0x09uy |] (runOf Z80Table.fd 0x09)
  let ADD_IX_DE =
    mkOp "ADD IX,DE" [| 0xDDuy; 0x19uy |] (runOf Z80Table.dd 0x19)
  let ADD_IY_DE =
    mkOp "ADD IY,DE" [| 0xFDuy; 0x19uy |] (runOf Z80Table.fd 0x19)
  let ADD_IX_HL =
    mkOp "ADD IX,HL" [| 0xDDuy; 0x29uy |] (runOf Z80Table.dd 0x29)
  let ADD_IY_HL =
    mkOp "ADD IY,HL" [| 0xFDuy; 0x29uy |] (runOf Z80Table.fd 0x29)
  let ADD_IX_SP =
    mkOp "ADD IX,SP" [| 0xDDuy; 0x39uy |] (runOf Z80Table.dd 0x39)
  let ADD_IY_SP =
    mkOp "ADD IY,SP" [| 0xFDuy; 0x39uy |] (runOf Z80Table.fd 0x39)
  let INC_B =
    mkOp "INC B" [| 0x04uy |] (runOf Z80Table.main 0x04)
  let DEC_B =
    mkOp "DEC B" [| 0x05uy |] (runOf Z80Table.main 0x05)
  let INC_C =
    mkOp "INC C" [| 0x0cuy |] (runOf Z80Table.main 0x0C)
  let DEC_C =
    mkOp "DEC C" [| 0x0duy |] (runOf Z80Table.main 0x0D)
  let INC_D =
    mkOp "INC D" [| 0x14uy |] (runOf Z80Table.main 0x14)
  let DEC_D =
    mkOp "DEC D" [| 0x15uy |] (runOf Z80Table.main 0x15)
  let INC_E =
    mkOp "INC E" [| 0x1cuy |] (runOf Z80Table.main 0x1C)
  let DEC_E =
    mkOp "DEC E" [| 0x1duy |] (runOf Z80Table.main 0x1D)
  let INC_H =
    mkOp "INC H" [| 0x24uy |] (runOf Z80Table.main 0x24)
  let DEC_H =
    mkOp "DEC H" [| 0x25uy |] (runOf Z80Table.main 0x25)
  let INC_L =
    mkOp "INC L" [| 0x2cuy |] (runOf Z80Table.main 0x2C)
  let DEC_L =
    mkOp "DEC L" [| 0x2duy |] (runOf Z80Table.main 0x2D)
  let INC_A =
    mkOp "INC A" [| 0x3cuy |] (runOf Z80Table.main 0x3C)
  let DEC_A =
    mkOp "DEC A" [| 0x3duy |] (runOf Z80Table.main 0x3D)
  let INC_PTR_HL =
    mkOp "INC (HL)" [| 0x34uy |] (runOf Z80Table.main 0x34)
  let DEC_PTR_HL =
    mkOp "DEC (HL)" [| 0x35uy |] (runOf Z80Table.main 0x35)
  let INC_PTR_IXd (d : int) =
    mkOp "INC (IX+d)" [| 0xdduy; 0x34uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x34)
  let DEC_PTR_IXd (d : int) =
    mkOp "DEC (IX+d)" [| 0xdduy; 0x35uy; byte (d &&& 0xFF) |] (runOf Z80Table.dd 0x35)
  let LD_PTR_IXd_n (d : int) (n : int) =
    mkOp "LD (IX+d),n" [| 0xdduy; 0x36uy; byte (d &&& 0xFF); byte (n &&& 0xFF) |] (runOf Z80Table.dd 0x36)
  let INC_BC =
    mkOp "INC BC" [| 0x03uy |] (runOf Z80Table.main 0x03)
  let DEC_BC =
    mkOp "DEC BC" [| 0x0buy |] (runOf Z80Table.main 0x0B)
  let INC_DE =
    mkOp "INC DE" [| 0x13uy |] (runOf Z80Table.main 0x13)
  let DEC_DE =
    mkOp "DEC DE" [| 0x1buy |] (runOf Z80Table.main 0x1B)
  let INC_HL =
    mkOp "INC HL" [| 0x23uy |] (runOf Z80Table.main 0x23)
  let DEC_HL =
    mkOp "DEC HL" [| 0x2buy |] (runOf Z80Table.main 0x2B)
  let INC_SP =
    mkOp "INC SP" [| 0x33uy |] (runOf Z80Table.main 0x33)
  let DEC_SP =
    mkOp "DEC SP" [| 0x3buy |] (runOf Z80Table.main 0x3B)
  let INC_IX =
    mkOp "INC IX" [| 0xDDuy; 0x23uy |] (runOf Z80Table.dd 0x23)
  let DEC_IX =
    mkOp "DEC IX" [| 0xDDuy; 0x2Buy |] (runOf Z80Table.dd 0x2B)
  let INC_IXH =
    mkOp "INC IXH" [| 0xDDuy; 0x24uy |] (runOf Z80Table.dd 0x24)
  let DEC_IXH =
    mkOp "DEC IXH" [| 0xDDuy; 0x25uy |] (runOf Z80Table.dd 0x25)
  let INC_IXL =
    mkOp "INC IXL" [| 0xDDuy; 0x2Cuy |] (runOf Z80Table.dd 0x2C)
  let DEC_IXL =
    mkOp "DEC IXL" [| 0xDDuy; 0x2Duy |] (runOf Z80Table.dd 0x2D)
  let PUSH_BC =
    mkOp "PUSH BC" [| 0xc5uy |] (runOf Z80Table.main 0xC5)
  let POP_BC =
    mkOp "POP BC" [| 0xc1uy |] (runOf Z80Table.main 0xC1)
  let PUSH_DE =
    mkOp "PUSH DE" [| 0xd5uy |] (runOf Z80Table.main 0xD5)
  let POP_DE =
    mkOp "POP DE" [| 0xd1uy |] (runOf Z80Table.main 0xD1)
  let PUSH_HL =
    mkOp "PUSH HL" [| 0xe5uy |] (runOf Z80Table.main 0xE5)
  let POP_HL =
    mkOp "POP HL" [| 0xe1uy |] (runOf Z80Table.main 0xE1)
  let PUSH_AF =
    mkOp "PUSH AF" [| 0xf5uy |] (runOf Z80Table.main 0xF5)
  let POP_AF =
    mkOp "POP AF" [| 0xf1uy |] (runOf Z80Table.main 0xF1)
  let PUSH_IX =
    mkOp "PUSH IX" [| 0xDDuy; 0xE5uy |] (runOf Z80Table.dd 0xE5)
  let POP_IX =
    mkOp "POP IX" [| 0xDDuy; 0xE1uy |] (runOf Z80Table.dd 0xE1)
  let RLC_B =
    mkOp "RLC B" [| 0xCBuy; 0x00uy |] (runOf Z80Table.cb 0x00)
  let RLC_C =
    mkOp "RLC C" [| 0xCBuy; 0x01uy |] (runOf Z80Table.cb 0x01)
  let RLC_D =
    mkOp "RLC D" [| 0xCBuy; 0x02uy |] (runOf Z80Table.cb 0x02)
  let RLC_E =
    mkOp "RLC E" [| 0xCBuy; 0x03uy |] (runOf Z80Table.cb 0x03)
  let RLC_H =
    mkOp "RLC H" [| 0xCBuy; 0x04uy |] (runOf Z80Table.cb 0x04)
  let RLC_L =
    mkOp "RLC L" [| 0xCBuy; 0x05uy |] (runOf Z80Table.cb 0x05)
  let RLC_A =
    mkOp "RLC A" [| 0xCBuy; 0x07uy |] (runOf Z80Table.cb 0x07)
  let RLC_PTR_HL =
    mkOp "RLC (HL)" [| 0xCBuy; 0x06uy |] (runOf Z80Table.cb 0x06)
  let RLC_PTR_IXd (d : int) =
    mkOp "RLC (IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x06uy |] (runOf Z80Table.dd_cb 0x06)
  let RLC_PTR_IYd (d : int) =
    mkOp "RLC (IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x06uy |] (runOf Z80Table.fd_cb 0x06)
  let RRC_B =
    mkOp "RRC B" [| 0xCBuy; 0x08uy |] (runOf Z80Table.cb 0x08)
  let RRC_C =
    mkOp "RRC C" [| 0xCBuy; 0x09uy |] (runOf Z80Table.cb 0x09)
  let RRC_D =
    mkOp "RRC D" [| 0xCBuy; 0x0auy |] (runOf Z80Table.cb 0x0A)
  let RRC_E =
    mkOp "RRC E" [| 0xCBuy; 0x0buy |] (runOf Z80Table.cb 0x0B)
  let RRC_H =
    mkOp "RRC H" [| 0xCBuy; 0x0cuy |] (runOf Z80Table.cb 0x0C)
  let RRC_L =
    mkOp "RRC L" [| 0xCBuy; 0x0duy |] (runOf Z80Table.cb 0x0D)
  let RRC_A =
    mkOp "RRC A" [| 0xCBuy; 0x0fuy |] (runOf Z80Table.cb 0x0F)
  let RRC_PTR_HL =
    mkOp "RRC (HL)" [| 0xCBuy; 0x0euy |] (runOf Z80Table.cb 0x0E)
  let RRC_PTR_IXd (d : int) =
    mkOp "RRC (IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x0euy |] (runOf Z80Table.dd_cb 0x0E)
  let RRC_PTR_IYd (d : int) =
    mkOp "RRC (IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x0euy |] (runOf Z80Table.fd_cb 0x0E)
  let RL_B =
    mkOp "RL B" [| 0xCBuy; 0x10uy |] (runOf Z80Table.cb 0x10)
  let RL_C =
    mkOp "RL C" [| 0xCBuy; 0x11uy |] (runOf Z80Table.cb 0x11)
  let RL_D =
    mkOp "RL D" [| 0xCBuy; 0x12uy |] (runOf Z80Table.cb 0x12)
  let RL_E =
    mkOp "RL E" [| 0xCBuy; 0x13uy |] (runOf Z80Table.cb 0x13)
  let RL_H =
    mkOp "RL H" [| 0xCBuy; 0x14uy |] (runOf Z80Table.cb 0x14)
  let RL_L =
    mkOp "RL L" [| 0xCBuy; 0x15uy |] (runOf Z80Table.cb 0x15)
  let RL_A =
    mkOp "RL A" [| 0xCBuy; 0x17uy |] (runOf Z80Table.cb 0x17)
  let RL_PTR_HL =
    mkOp "RL (HL)" [| 0xCBuy; 0x16uy |] (runOf Z80Table.cb 0x16)
  let RL_PTR_IXd (d : int) =
    mkOp "RL (IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x16uy |] (runOf Z80Table.dd_cb 0x16)
  let RL_PTR_IYd (d : int) =
    mkOp "RL (IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x16uy |] (runOf Z80Table.fd_cb 0x16)
  let RR_B =
    mkOp "RR B" [| 0xCBuy; 0x18uy |] (runOf Z80Table.cb 0x18)
  let RR_C =
    mkOp "RR C" [| 0xCBuy; 0x19uy |] (runOf Z80Table.cb 0x19)
  let RR_D =
    mkOp "RR D" [| 0xCBuy; 0x1auy |] (runOf Z80Table.cb 0x1A)
  let RR_E =
    mkOp "RR E" [| 0xCBuy; 0x1buy |] (runOf Z80Table.cb 0x1B)
  let RR_H =
    mkOp "RR H" [| 0xCBuy; 0x1cuy |] (runOf Z80Table.cb 0x1C)
  let RR_L =
    mkOp "RR L" [| 0xCBuy; 0x1duy |] (runOf Z80Table.cb 0x1D)
  let RR_A =
    mkOp "RR A" [| 0xCBuy; 0x1fuy |] (runOf Z80Table.cb 0x1F)
  let RR_PTR_HL =
    mkOp "RR (HL)" [| 0xCBuy; 0x1euy |] (runOf Z80Table.cb 0x1E)
  let RR_PTR_IXd (d : int) =
    mkOp "RR (IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x1euy |] (runOf Z80Table.dd_cb 0x1E)
  let RR_PTR_IYd (d : int) =
    mkOp "RR (IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x1euy |] (runOf Z80Table.fd_cb 0x1E)
  let SLA_B =
    mkOp "SLA B" [| 0xCBuy; 0x20uy |] (runOf Z80Table.cb 0x20)
  let SLA_C =
    mkOp "SLA C" [| 0xCBuy; 0x21uy |] (runOf Z80Table.cb 0x21)
  let SLA_D =
    mkOp "SLA D" [| 0xCBuy; 0x22uy |] (runOf Z80Table.cb 0x22)
  let SLA_E =
    mkOp "SLA E" [| 0xCBuy; 0x23uy |] (runOf Z80Table.cb 0x23)
  let SLA_H =
    mkOp "SLA H" [| 0xCBuy; 0x24uy |] (runOf Z80Table.cb 0x24)
  let SLA_L =
    mkOp "SLA L" [| 0xCBuy; 0x25uy |] (runOf Z80Table.cb 0x25)
  let SLA_A =
    mkOp "SLA A" [| 0xCBuy; 0x27uy |] (runOf Z80Table.cb 0x27)
  let SLA_PTR_HL =
    mkOp "SLA (HL)" [| 0xCBuy; 0x26uy |] (runOf Z80Table.cb 0x26)
  let SLA_PTR_IXd (d : int) =
    mkOp "SLA (IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x26uy |] (runOf Z80Table.dd_cb 0x26)
  let SLA_PTR_IYd (d : int) =
    mkOp "SLA (IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x26uy |] (runOf Z80Table.fd_cb 0x26)
  let SRA_B =
    mkOp "SRA B" [| 0xCBuy; 0x28uy |] (runOf Z80Table.cb 0x28)
  let SRA_C =
    mkOp "SRA C" [| 0xCBuy; 0x29uy |] (runOf Z80Table.cb 0x29)
  let SRA_D =
    mkOp "SRA D" [| 0xCBuy; 0x2auy |] (runOf Z80Table.cb 0x2A)
  let SRA_E =
    mkOp "SRA E" [| 0xCBuy; 0x2buy |] (runOf Z80Table.cb 0x2B)
  let SRA_H =
    mkOp "SRA H" [| 0xCBuy; 0x2cuy |] (runOf Z80Table.cb 0x2C)
  let SRA_L =
    mkOp "SRA L" [| 0xCBuy; 0x2duy |] (runOf Z80Table.cb 0x2D)
  let SRA_A =
    mkOp "SRA A" [| 0xCBuy; 0x2fuy |] (runOf Z80Table.cb 0x2F)
  let SRA_PTR_HL =
    mkOp "SRA (HL)" [| 0xCBuy; 0x2euy |] (runOf Z80Table.cb 0x2E)
  let SRA_PTR_IXd (d : int) =
    mkOp "SRA (IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x2euy |] (runOf Z80Table.dd_cb 0x2E)
  let SRA_PTR_IYd (d : int) =
    mkOp "SRA (IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x2euy |] (runOf Z80Table.fd_cb 0x2E)
  let SRL_B =
    mkOp "SRL B" [| 0xCBuy; 0x38uy |] (runOf Z80Table.cb 0x38)
  let SRL_C =
    mkOp "SRL C" [| 0xCBuy; 0x39uy |] (runOf Z80Table.cb 0x39)
  let SRL_D =
    mkOp "SRL D" [| 0xCBuy; 0x3auy |] (runOf Z80Table.cb 0x3A)
  let SRL_E =
    mkOp "SRL E" [| 0xCBuy; 0x3buy |] (runOf Z80Table.cb 0x3B)
  let SRL_H =
    mkOp "SRL H" [| 0xCBuy; 0x3cuy |] (runOf Z80Table.cb 0x3C)
  let SRL_L =
    mkOp "SRL L" [| 0xCBuy; 0x3duy |] (runOf Z80Table.cb 0x3D)
  let SRL_A =
    mkOp "SRL A" [| 0xCBuy; 0x3fuy |] (runOf Z80Table.cb 0x3F)
  let SRL_PTR_HL =
    mkOp "SRL (HL)" [| 0xCBuy; 0x3euy |] (runOf Z80Table.cb 0x3E)
  let SRL_PTR_IXd (d : int) =
    mkOp "SRL (IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x3euy |] (runOf Z80Table.dd_cb 0x3E)
  let SRL_PTR_IYd (d : int) =
    mkOp "SRL (IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x3euy |] (runOf Z80Table.fd_cb 0x3E)
  let BIT0_B =
    mkOp "BIT 0,B" [| 0xCBuy; 0x40uy |] (runOf Z80Table.cb 0x40)
  let BIT0_C =
    mkOp "BIT 0,C" [| 0xCBuy; 0x41uy |] (runOf Z80Table.cb 0x41)
  let BIT0_D =
    mkOp "BIT 0,D" [| 0xCBuy; 0x42uy |] (runOf Z80Table.cb 0x42)
  let BIT0_E =
    mkOp "BIT 0,E" [| 0xCBuy; 0x43uy |] (runOf Z80Table.cb 0x43)
  let BIT0_H =
    mkOp "BIT 0,H" [| 0xCBuy; 0x44uy |] (runOf Z80Table.cb 0x44)
  let BIT0_L =
    mkOp "BIT 0,L" [| 0xCBuy; 0x45uy |] (runOf Z80Table.cb 0x45)
  let BIT0_A =
    mkOp "BIT 0,A" [| 0xCBuy; 0x47uy |] (runOf Z80Table.cb 0x47)
  let BIT0_PTR_HL =
    mkOp "BIT 0,(HL)" [| 0xCBuy; 0x46uy |] (runOf Z80Table.cb 0x46)
  let BIT0_PTR_IXd (d : int) =
    mkOp "BIT 0,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x46uy |] (runOf Z80Table.dd_cb 0x46)
  let BIT0_PTR_IYd (d : int) =
    mkOp "BIT 0,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x46uy |] (runOf Z80Table.fd_cb 0x46)
  let RES0_B =
    mkOp "RES 0,B" [| 0xCBuy; 0x80uy |] (runOf Z80Table.cb 0x80)
  let RES0_C =
    mkOp "RES 0,C" [| 0xCBuy; 0x81uy |] (runOf Z80Table.cb 0x81)
  let RES0_D =
    mkOp "RES 0,D" [| 0xCBuy; 0x82uy |] (runOf Z80Table.cb 0x82)
  let RES0_E =
    mkOp "RES 0,E" [| 0xCBuy; 0x83uy |] (runOf Z80Table.cb 0x83)
  let RES0_H =
    mkOp "RES 0,H" [| 0xCBuy; 0x84uy |] (runOf Z80Table.cb 0x84)
  let RES0_L =
    mkOp "RES 0,L" [| 0xCBuy; 0x85uy |] (runOf Z80Table.cb 0x85)
  let RES0_A =
    mkOp "RES 0,A" [| 0xCBuy; 0x87uy |] (runOf Z80Table.cb 0x87)
  let RES0_PTR_HL =
    mkOp "RES 0,(HL)" [| 0xCBuy; 0x86uy |] (runOf Z80Table.cb 0x86)
  let RES0_PTR_IXd (d : int) =
    mkOp "RES 0,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x86uy |] (runOf Z80Table.dd_cb 0x86)
  let RES0_PTR_IYd (d : int) =
    mkOp "RES 0,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x86uy |] (runOf Z80Table.fd_cb 0x86)
  let SET0_B =
    mkOp "SET 0,B" [| 0xCBuy; 0xc0uy |] (runOf Z80Table.cb 0xC0)
  let SET0_C =
    mkOp "SET 0,C" [| 0xCBuy; 0xc1uy |] (runOf Z80Table.cb 0xC1)
  let SET0_D =
    mkOp "SET 0,D" [| 0xCBuy; 0xc2uy |] (runOf Z80Table.cb 0xC2)
  let SET0_E =
    mkOp "SET 0,E" [| 0xCBuy; 0xc3uy |] (runOf Z80Table.cb 0xC3)
  let SET0_H =
    mkOp "SET 0,H" [| 0xCBuy; 0xc4uy |] (runOf Z80Table.cb 0xC4)
  let SET0_L =
    mkOp "SET 0,L" [| 0xCBuy; 0xc5uy |] (runOf Z80Table.cb 0xC5)
  let SET0_A =
    mkOp "SET 0,A" [| 0xCBuy; 0xc7uy |] (runOf Z80Table.cb 0xC7)
  let SET0_PTR_HL =
    mkOp "SET 0,(HL)" [| 0xCBuy; 0xc6uy |] (runOf Z80Table.cb 0xC6)
  let SET0_PTR_IXd (d : int) =
    mkOp "SET 0,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xc6uy |] (runOf Z80Table.dd_cb 0xC6)
  let SET0_PTR_IYd (d : int) =
    mkOp "SET 0,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xc6uy |] (runOf Z80Table.fd_cb 0xC6)
  let BIT1_B =
    mkOp "BIT 1,B" [| 0xCBuy; 0x48uy |] (runOf Z80Table.cb 0x48)
  let BIT1_C =
    mkOp "BIT 1,C" [| 0xCBuy; 0x49uy |] (runOf Z80Table.cb 0x49)
  let BIT1_D =
    mkOp "BIT 1,D" [| 0xCBuy; 0x4auy |] (runOf Z80Table.cb 0x4A)
  let BIT1_E =
    mkOp "BIT 1,E" [| 0xCBuy; 0x4buy |] (runOf Z80Table.cb 0x4B)
  let BIT1_H =
    mkOp "BIT 1,H" [| 0xCBuy; 0x4cuy |] (runOf Z80Table.cb 0x4C)
  let BIT1_L =
    mkOp "BIT 1,L" [| 0xCBuy; 0x4duy |] (runOf Z80Table.cb 0x4D)
  let BIT1_A =
    mkOp "BIT 1,A" [| 0xCBuy; 0x4fuy |] (runOf Z80Table.cb 0x4F)
  let BIT1_PTR_HL =
    mkOp "BIT 1,(HL)" [| 0xCBuy; 0x4euy |] (runOf Z80Table.cb 0x4E)
  let BIT1_PTR_IXd (d : int) =
    mkOp "BIT 1,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x4euy |] (runOf Z80Table.dd_cb 0x4E)
  let BIT1_PTR_IYd (d : int) =
    mkOp "BIT 1,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x4euy |] (runOf Z80Table.fd_cb 0x4E)
  let RES1_B =
    mkOp "RES 1,B" [| 0xCBuy; 0x88uy |] (runOf Z80Table.cb 0x88)
  let RES1_C =
    mkOp "RES 1,C" [| 0xCBuy; 0x89uy |] (runOf Z80Table.cb 0x89)
  let RES1_D =
    mkOp "RES 1,D" [| 0xCBuy; 0x8auy |] (runOf Z80Table.cb 0x8A)
  let RES1_E =
    mkOp "RES 1,E" [| 0xCBuy; 0x8buy |] (runOf Z80Table.cb 0x8B)
  let RES1_H =
    mkOp "RES 1,H" [| 0xCBuy; 0x8cuy |] (runOf Z80Table.cb 0x8C)
  let RES1_L =
    mkOp "RES 1,L" [| 0xCBuy; 0x8duy |] (runOf Z80Table.cb 0x8D)
  let RES1_A =
    mkOp "RES 1,A" [| 0xCBuy; 0x8fuy |] (runOf Z80Table.cb 0x8F)
  let RES1_PTR_HL =
    mkOp "RES 1,(HL)" [| 0xCBuy; 0x8euy |] (runOf Z80Table.cb 0x8E)
  let RES1_PTR_IXd (d : int) =
    mkOp "RES 1,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x8euy |] (runOf Z80Table.dd_cb 0x8E)
  let RES1_PTR_IYd (d : int) =
    mkOp "RES 1,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x8euy |] (runOf Z80Table.fd_cb 0x8E)
  let SET1_B =
    mkOp "SET 1,B" [| 0xCBuy; 0xc8uy |] (runOf Z80Table.cb 0xC8)
  let SET1_C =
    mkOp "SET 1,C" [| 0xCBuy; 0xc9uy |] (runOf Z80Table.cb 0xC9)
  let SET1_D =
    mkOp "SET 1,D" [| 0xCBuy; 0xcauy |] (runOf Z80Table.cb 0xCA)
  let SET1_E =
    mkOp "SET 1,E" [| 0xCBuy; 0xcbuy |] (runOf Z80Table.cb 0xCB)
  let SET1_H =
    mkOp "SET 1,H" [| 0xCBuy; 0xccuy |] (runOf Z80Table.cb 0xCC)
  let SET1_L =
    mkOp "SET 1,L" [| 0xCBuy; 0xcduy |] (runOf Z80Table.cb 0xCD)
  let SET1_A =
    mkOp "SET 1,A" [| 0xCBuy; 0xcfuy |] (runOf Z80Table.cb 0xCF)
  let SET1_PTR_HL =
    mkOp "SET 1,(HL)" [| 0xCBuy; 0xceuy |] (runOf Z80Table.cb 0xCE)
  let SET1_PTR_IXd (d : int) =
    mkOp "SET 1,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xceuy |] (runOf Z80Table.dd_cb 0xCE)
  let SET1_PTR_IYd (d : int) =
    mkOp "SET 1,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xceuy |] (runOf Z80Table.fd_cb 0xCE)
  let BIT2_B =
    mkOp "BIT 2,B" [| 0xCBuy; 0x50uy |] (runOf Z80Table.cb 0x50)
  let BIT2_C =
    mkOp "BIT 2,C" [| 0xCBuy; 0x51uy |] (runOf Z80Table.cb 0x51)
  let BIT2_D =
    mkOp "BIT 2,D" [| 0xCBuy; 0x52uy |] (runOf Z80Table.cb 0x52)
  let BIT2_E =
    mkOp "BIT 2,E" [| 0xCBuy; 0x53uy |] (runOf Z80Table.cb 0x53)
  let BIT2_H =
    mkOp "BIT 2,H" [| 0xCBuy; 0x54uy |] (runOf Z80Table.cb 0x54)
  let BIT2_L =
    mkOp "BIT 2,L" [| 0xCBuy; 0x55uy |] (runOf Z80Table.cb 0x55)
  let BIT2_A =
    mkOp "BIT 2,A" [| 0xCBuy; 0x57uy |] (runOf Z80Table.cb 0x57)
  let BIT2_PTR_HL =
    mkOp "BIT 2,(HL)" [| 0xCBuy; 0x56uy |] (runOf Z80Table.cb 0x56)
  let BIT2_PTR_IXd (d : int) =
    mkOp "BIT 2,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x56uy |] (runOf Z80Table.dd_cb 0x56)
  let BIT2_PTR_IYd (d : int) =
    mkOp "BIT 2,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x56uy |] (runOf Z80Table.fd_cb 0x56)
  let RES2_B =
    mkOp "RES 2,B" [| 0xCBuy; 0x90uy |] (runOf Z80Table.cb 0x90)
  let RES2_C =
    mkOp "RES 2,C" [| 0xCBuy; 0x91uy |] (runOf Z80Table.cb 0x91)
  let RES2_D =
    mkOp "RES 2,D" [| 0xCBuy; 0x92uy |] (runOf Z80Table.cb 0x92)
  let RES2_E =
    mkOp "RES 2,E" [| 0xCBuy; 0x93uy |] (runOf Z80Table.cb 0x93)
  let RES2_H =
    mkOp "RES 2,H" [| 0xCBuy; 0x94uy |] (runOf Z80Table.cb 0x94)
  let RES2_L =
    mkOp "RES 2,L" [| 0xCBuy; 0x95uy |] (runOf Z80Table.cb 0x95)
  let RES2_A =
    mkOp "RES 2,A" [| 0xCBuy; 0x97uy |] (runOf Z80Table.cb 0x97)
  let RES2_PTR_HL =
    mkOp "RES 2,(HL)" [| 0xCBuy; 0x96uy |] (runOf Z80Table.cb 0x96)
  let RES2_PTR_IXd (d : int) =
    mkOp "RES 2,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x96uy |] (runOf Z80Table.dd_cb 0x96)
  let RES2_PTR_IYd (d : int) =
    mkOp "RES 2,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x96uy |] (runOf Z80Table.fd_cb 0x96)
  let SET2_B =
    mkOp "SET 2,B" [| 0xCBuy; 0xd0uy |] (runOf Z80Table.cb 0xD0)
  let SET2_C =
    mkOp "SET 2,C" [| 0xCBuy; 0xd1uy |] (runOf Z80Table.cb 0xD1)
  let SET2_D =
    mkOp "SET 2,D" [| 0xCBuy; 0xd2uy |] (runOf Z80Table.cb 0xD2)
  let SET2_E =
    mkOp "SET 2,E" [| 0xCBuy; 0xd3uy |] (runOf Z80Table.cb 0xD3)
  let SET2_H =
    mkOp "SET 2,H" [| 0xCBuy; 0xd4uy |] (runOf Z80Table.cb 0xD4)
  let SET2_L =
    mkOp "SET 2,L" [| 0xCBuy; 0xd5uy |] (runOf Z80Table.cb 0xD5)
  let SET2_A =
    mkOp "SET 2,A" [| 0xCBuy; 0xd7uy |] (runOf Z80Table.cb 0xD7)
  let SET2_PTR_HL =
    mkOp "SET 2,(HL)" [| 0xCBuy; 0xd6uy |] (runOf Z80Table.cb 0xD6)
  let SET2_PTR_IXd (d : int) =
    mkOp "SET 2,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xd6uy |] (runOf Z80Table.dd_cb 0xD6)
  let SET2_PTR_IYd (d : int) =
    mkOp "SET 2,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xd6uy |] (runOf Z80Table.fd_cb 0xD6)
  let BIT3_B =
    mkOp "BIT 3,B" [| 0xCBuy; 0x58uy |] (runOf Z80Table.cb 0x58)
  let BIT3_C =
    mkOp "BIT 3,C" [| 0xCBuy; 0x59uy |] (runOf Z80Table.cb 0x59)
  let BIT3_D =
    mkOp "BIT 3,D" [| 0xCBuy; 0x5auy |] (runOf Z80Table.cb 0x5A)
  let BIT3_E =
    mkOp "BIT 3,E" [| 0xCBuy; 0x5buy |] (runOf Z80Table.cb 0x5B)
  let BIT3_H =
    mkOp "BIT 3,H" [| 0xCBuy; 0x5cuy |] (runOf Z80Table.cb 0x5C)
  let BIT3_L =
    mkOp "BIT 3,L" [| 0xCBuy; 0x5duy |] (runOf Z80Table.cb 0x5D)
  let BIT3_A =
    mkOp "BIT 3,A" [| 0xCBuy; 0x5fuy |] (runOf Z80Table.cb 0x5F)
  let BIT3_PTR_HL =
    mkOp "BIT 3,(HL)" [| 0xCBuy; 0x5euy |] (runOf Z80Table.cb 0x5E)
  let BIT3_PTR_IXd (d : int) =
    mkOp "BIT 3,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x5euy |] (runOf Z80Table.dd_cb 0x5E)
  let BIT3_PTR_IYd (d : int) =
    mkOp "BIT 3,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x5euy |] (runOf Z80Table.fd_cb 0x5E)
  let RES3_B =
    mkOp "RES 3,B" [| 0xCBuy; 0x98uy |] (runOf Z80Table.cb 0x98)
  let RES3_C =
    mkOp "RES 3,C" [| 0xCBuy; 0x99uy |] (runOf Z80Table.cb 0x99)
  let RES3_D =
    mkOp "RES 3,D" [| 0xCBuy; 0x9auy |] (runOf Z80Table.cb 0x9A)
  let RES3_E =
    mkOp "RES 3,E" [| 0xCBuy; 0x9buy |] (runOf Z80Table.cb 0x9B)
  let RES3_H =
    mkOp "RES 3,H" [| 0xCBuy; 0x9cuy |] (runOf Z80Table.cb 0x9C)
  let RES3_L =
    mkOp "RES 3,L" [| 0xCBuy; 0x9duy |] (runOf Z80Table.cb 0x9D)
  let RES3_A =
    mkOp "RES 3,A" [| 0xCBuy; 0x9fuy |] (runOf Z80Table.cb 0x9F)
  let RES3_PTR_HL =
    mkOp "RES 3,(HL)" [| 0xCBuy; 0x9euy |] (runOf Z80Table.cb 0x9E)
  let RES3_PTR_IXd (d : int) =
    mkOp "RES 3,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x9euy |] (runOf Z80Table.dd_cb 0x9E)
  let RES3_PTR_IYd (d : int) =
    mkOp "RES 3,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x9euy |] (runOf Z80Table.fd_cb 0x9E)
  let SET3_B =
    mkOp "SET 3,B" [| 0xCBuy; 0xd8uy |] (runOf Z80Table.cb 0xD8)
  let SET3_C =
    mkOp "SET 3,C" [| 0xCBuy; 0xd9uy |] (runOf Z80Table.cb 0xD9)
  let SET3_D =
    mkOp "SET 3,D" [| 0xCBuy; 0xdauy |] (runOf Z80Table.cb 0xDA)
  let SET3_E =
    mkOp "SET 3,E" [| 0xCBuy; 0xdbuy |] (runOf Z80Table.cb 0xDB)
  let SET3_H =
    mkOp "SET 3,H" [| 0xCBuy; 0xdcuy |] (runOf Z80Table.cb 0xDC)
  let SET3_L =
    mkOp "SET 3,L" [| 0xCBuy; 0xdduy |] (runOf Z80Table.cb 0xDD)
  let SET3_A =
    mkOp "SET 3,A" [| 0xCBuy; 0xdfuy |] (runOf Z80Table.cb 0xDF)
  let SET3_PTR_HL =
    mkOp "SET 3,(HL)" [| 0xCBuy; 0xdeuy |] (runOf Z80Table.cb 0xDE)
  let SET3_PTR_IXd (d : int) =
    mkOp "SET 3,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xdeuy |] (runOf Z80Table.dd_cb 0xDE)
  let SET3_PTR_IYd (d : int) =
    mkOp "SET 3,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xdeuy |] (runOf Z80Table.fd_cb 0xDE)
  let BIT4_B =
    mkOp "BIT 4,B" [| 0xCBuy; 0x60uy |] (runOf Z80Table.cb 0x60)
  let BIT4_C =
    mkOp "BIT 4,C" [| 0xCBuy; 0x61uy |] (runOf Z80Table.cb 0x61)
  let BIT4_D =
    mkOp "BIT 4,D" [| 0xCBuy; 0x62uy |] (runOf Z80Table.cb 0x62)
  let BIT4_E =
    mkOp "BIT 4,E" [| 0xCBuy; 0x63uy |] (runOf Z80Table.cb 0x63)
  let BIT4_H =
    mkOp "BIT 4,H" [| 0xCBuy; 0x64uy |] (runOf Z80Table.cb 0x64)
  let BIT4_L =
    mkOp "BIT 4,L" [| 0xCBuy; 0x65uy |] (runOf Z80Table.cb 0x65)
  let BIT4_A =
    mkOp "BIT 4,A" [| 0xCBuy; 0x67uy |] (runOf Z80Table.cb 0x67)
  let BIT4_PTR_HL =
    mkOp "BIT 4,(HL)" [| 0xCBuy; 0x66uy |] (runOf Z80Table.cb 0x66)
  let BIT4_PTR_IXd (d : int) =
    mkOp "BIT 4,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x66uy |] (runOf Z80Table.dd_cb 0x66)
  let BIT4_PTR_IYd (d : int) =
    mkOp "BIT 4,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x66uy |] (runOf Z80Table.fd_cb 0x66)
  let RES4_B =
    mkOp "RES 4,B" [| 0xCBuy; 0xa0uy |] (runOf Z80Table.cb 0xA0)
  let RES4_C =
    mkOp "RES 4,C" [| 0xCBuy; 0xa1uy |] (runOf Z80Table.cb 0xA1)
  let RES4_D =
    mkOp "RES 4,D" [| 0xCBuy; 0xa2uy |] (runOf Z80Table.cb 0xA2)
  let RES4_E =
    mkOp "RES 4,E" [| 0xCBuy; 0xa3uy |] (runOf Z80Table.cb 0xA3)
  let RES4_H =
    mkOp "RES 4,H" [| 0xCBuy; 0xa4uy |] (runOf Z80Table.cb 0xA4)
  let RES4_L =
    mkOp "RES 4,L" [| 0xCBuy; 0xa5uy |] (runOf Z80Table.cb 0xA5)
  let RES4_A =
    mkOp "RES 4,A" [| 0xCBuy; 0xa7uy |] (runOf Z80Table.cb 0xA7)
  let RES4_PTR_HL =
    mkOp "RES 4,(HL)" [| 0xCBuy; 0xa6uy |] (runOf Z80Table.cb 0xA6)
  let RES4_PTR_IXd (d : int) =
    mkOp "RES 4,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xa6uy |] (runOf Z80Table.dd_cb 0xA6)
  let RES4_PTR_IYd (d : int) =
    mkOp "RES 4,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xa6uy |] (runOf Z80Table.fd_cb 0xA6)
  let SET4_B =
    mkOp "SET 4,B" [| 0xCBuy; 0xe0uy |] (runOf Z80Table.cb 0xE0)
  let SET4_C =
    mkOp "SET 4,C" [| 0xCBuy; 0xe1uy |] (runOf Z80Table.cb 0xE1)
  let SET4_D =
    mkOp "SET 4,D" [| 0xCBuy; 0xe2uy |] (runOf Z80Table.cb 0xE2)
  let SET4_E =
    mkOp "SET 4,E" [| 0xCBuy; 0xe3uy |] (runOf Z80Table.cb 0xE3)
  let SET4_H =
    mkOp "SET 4,H" [| 0xCBuy; 0xe4uy |] (runOf Z80Table.cb 0xE4)
  let SET4_L =
    mkOp "SET 4,L" [| 0xCBuy; 0xe5uy |] (runOf Z80Table.cb 0xE5)
  let SET4_A =
    mkOp "SET 4,A" [| 0xCBuy; 0xe7uy |] (runOf Z80Table.cb 0xE7)
  let SET4_PTR_HL =
    mkOp "SET 4,(HL)" [| 0xCBuy; 0xe6uy |] (runOf Z80Table.cb 0xE6)
  let SET4_PTR_IXd (d : int) =
    mkOp "SET 4,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xe6uy |] (runOf Z80Table.dd_cb 0xE6)
  let SET4_PTR_IYd (d : int) =
    mkOp "SET 4,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xe6uy |] (runOf Z80Table.fd_cb 0xE6)
  let BIT5_B =
    mkOp "BIT 5,B" [| 0xCBuy; 0x68uy |] (runOf Z80Table.cb 0x68)
  let BIT5_C =
    mkOp "BIT 5,C" [| 0xCBuy; 0x69uy |] (runOf Z80Table.cb 0x69)
  let BIT5_D =
    mkOp "BIT 5,D" [| 0xCBuy; 0x6auy |] (runOf Z80Table.cb 0x6A)
  let BIT5_E =
    mkOp "BIT 5,E" [| 0xCBuy; 0x6buy |] (runOf Z80Table.cb 0x6B)
  let BIT5_H =
    mkOp "BIT 5,H" [| 0xCBuy; 0x6cuy |] (runOf Z80Table.cb 0x6C)
  let BIT5_L =
    mkOp "BIT 5,L" [| 0xCBuy; 0x6duy |] (runOf Z80Table.cb 0x6D)
  let BIT5_A =
    mkOp "BIT 5,A" [| 0xCBuy; 0x6fuy |] (runOf Z80Table.cb 0x6F)
  let BIT5_PTR_HL =
    mkOp "BIT 5,(HL)" [| 0xCBuy; 0x6euy |] (runOf Z80Table.cb 0x6E)
  let BIT5_PTR_IXd (d : int) =
    mkOp "BIT 5,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x6euy |] (runOf Z80Table.dd_cb 0x6E)
  let BIT5_PTR_IYd (d : int) =
    mkOp "BIT 5,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x6euy |] (runOf Z80Table.fd_cb 0x6E)
  let RES5_B =
    mkOp "RES 5,B" [| 0xCBuy; 0xa8uy |] (runOf Z80Table.cb 0xA8)
  let RES5_C =
    mkOp "RES 5,C" [| 0xCBuy; 0xa9uy |] (runOf Z80Table.cb 0xA9)
  let RES5_D =
    mkOp "RES 5,D" [| 0xCBuy; 0xaauy |] (runOf Z80Table.cb 0xAA)
  let RES5_E =
    mkOp "RES 5,E" [| 0xCBuy; 0xabuy |] (runOf Z80Table.cb 0xAB)
  let RES5_H =
    mkOp "RES 5,H" [| 0xCBuy; 0xacuy |] (runOf Z80Table.cb 0xAC)
  let RES5_L =
    mkOp "RES 5,L" [| 0xCBuy; 0xaduy |] (runOf Z80Table.cb 0xAD)
  let RES5_A =
    mkOp "RES 5,A" [| 0xCBuy; 0xafuy |] (runOf Z80Table.cb 0xAF)
  let RES5_PTR_HL =
    mkOp "RES 5,(HL)" [| 0xCBuy; 0xaeuy |] (runOf Z80Table.cb 0xAE)
  let RES5_PTR_IXd (d : int) =
    mkOp "RES 5,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xaeuy |] (runOf Z80Table.dd_cb 0xAE)
  let RES5_PTR_IYd (d : int) =
    mkOp "RES 5,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xaeuy |] (runOf Z80Table.fd_cb 0xAE)
  let SET5_B =
    mkOp "SET 5,B" [| 0xCBuy; 0xe8uy |] (runOf Z80Table.cb 0xE8)
  let SET5_C =
    mkOp "SET 5,C" [| 0xCBuy; 0xe9uy |] (runOf Z80Table.cb 0xE9)
  let SET5_D =
    mkOp "SET 5,D" [| 0xCBuy; 0xeauy |] (runOf Z80Table.cb 0xEA)
  let SET5_E =
    mkOp "SET 5,E" [| 0xCBuy; 0xebuy |] (runOf Z80Table.cb 0xEB)
  let SET5_H =
    mkOp "SET 5,H" [| 0xCBuy; 0xecuy |] (runOf Z80Table.cb 0xEC)
  let SET5_L =
    mkOp "SET 5,L" [| 0xCBuy; 0xeduy |] (runOf Z80Table.cb 0xED)
  let SET5_A =
    mkOp "SET 5,A" [| 0xCBuy; 0xefuy |] (runOf Z80Table.cb 0xEF)
  let SET5_PTR_HL =
    mkOp "SET 5,(HL)" [| 0xCBuy; 0xeeuy |] (runOf Z80Table.cb 0xEE)
  let SET5_PTR_IXd (d : int) =
    mkOp "SET 5,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xeeuy |] (runOf Z80Table.dd_cb 0xEE)
  let SET5_PTR_IYd (d : int) =
    mkOp "SET 5,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xeeuy |] (runOf Z80Table.fd_cb 0xEE)
  let BIT6_B =
    mkOp "BIT 6,B" [| 0xCBuy; 0x70uy |] (runOf Z80Table.cb 0x70)
  let BIT6_C =
    mkOp "BIT 6,C" [| 0xCBuy; 0x71uy |] (runOf Z80Table.cb 0x71)
  let BIT6_D =
    mkOp "BIT 6,D" [| 0xCBuy; 0x72uy |] (runOf Z80Table.cb 0x72)
  let BIT6_E =
    mkOp "BIT 6,E" [| 0xCBuy; 0x73uy |] (runOf Z80Table.cb 0x73)
  let BIT6_H =
    mkOp "BIT 6,H" [| 0xCBuy; 0x74uy |] (runOf Z80Table.cb 0x74)
  let BIT6_L =
    mkOp "BIT 6,L" [| 0xCBuy; 0x75uy |] (runOf Z80Table.cb 0x75)
  let BIT6_A =
    mkOp "BIT 6,A" [| 0xCBuy; 0x77uy |] (runOf Z80Table.cb 0x77)
  let BIT6_PTR_HL =
    mkOp "BIT 6,(HL)" [| 0xCBuy; 0x76uy |] (runOf Z80Table.cb 0x76)
  let BIT6_PTR_IXd (d : int) =
    mkOp "BIT 6,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x76uy |] (runOf Z80Table.dd_cb 0x76)
  let BIT6_PTR_IYd (d : int) =
    mkOp "BIT 6,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x76uy |] (runOf Z80Table.fd_cb 0x76)
  let RES6_B =
    mkOp "RES 6,B" [| 0xCBuy; 0xb0uy |] (runOf Z80Table.cb 0xB0)
  let RES6_C =
    mkOp "RES 6,C" [| 0xCBuy; 0xb1uy |] (runOf Z80Table.cb 0xB1)
  let RES6_D =
    mkOp "RES 6,D" [| 0xCBuy; 0xb2uy |] (runOf Z80Table.cb 0xB2)
  let RES6_E =
    mkOp "RES 6,E" [| 0xCBuy; 0xb3uy |] (runOf Z80Table.cb 0xB3)
  let RES6_H =
    mkOp "RES 6,H" [| 0xCBuy; 0xb4uy |] (runOf Z80Table.cb 0xB4)
  let RES6_L =
    mkOp "RES 6,L" [| 0xCBuy; 0xb5uy |] (runOf Z80Table.cb 0xB5)
  let RES6_A =
    mkOp "RES 6,A" [| 0xCBuy; 0xb7uy |] (runOf Z80Table.cb 0xB7)
  let RES6_PTR_HL =
    mkOp "RES 6,(HL)" [| 0xCBuy; 0xb6uy |] (runOf Z80Table.cb 0xB6)
  let RES6_PTR_IXd (d : int) =
    mkOp "RES 6,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xb6uy |] (runOf Z80Table.dd_cb 0xB6)
  let RES6_PTR_IYd (d : int) =
    mkOp "RES 6,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xb6uy |] (runOf Z80Table.fd_cb 0xB6)
  let SET6_B =
    mkOp "SET 6,B" [| 0xCBuy; 0xf0uy |] (runOf Z80Table.cb 0xF0)
  let SET6_C =
    mkOp "SET 6,C" [| 0xCBuy; 0xf1uy |] (runOf Z80Table.cb 0xF1)
  let SET6_D =
    mkOp "SET 6,D" [| 0xCBuy; 0xf2uy |] (runOf Z80Table.cb 0xF2)
  let SET6_E =
    mkOp "SET 6,E" [| 0xCBuy; 0xf3uy |] (runOf Z80Table.cb 0xF3)
  let SET6_H =
    mkOp "SET 6,H" [| 0xCBuy; 0xf4uy |] (runOf Z80Table.cb 0xF4)
  let SET6_L =
    mkOp "SET 6,L" [| 0xCBuy; 0xf5uy |] (runOf Z80Table.cb 0xF5)
  let SET6_A =
    mkOp "SET 6,A" [| 0xCBuy; 0xf7uy |] (runOf Z80Table.cb 0xF7)
  let SET6_PTR_HL =
    mkOp "SET 6,(HL)" [| 0xCBuy; 0xf6uy |] (runOf Z80Table.cb 0xF6)
  let SET6_PTR_IXd (d : int) =
    mkOp "SET 6,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xf6uy |] (runOf Z80Table.dd_cb 0xF6)
  let SET6_PTR_IYd (d : int) =
    mkOp "SET 6,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xf6uy |] (runOf Z80Table.fd_cb 0xF6)
  let BIT7_B =
    mkOp "BIT 7,B" [| 0xCBuy; 0x78uy |] (runOf Z80Table.cb 0x78)
  let BIT7_C =
    mkOp "BIT 7,C" [| 0xCBuy; 0x79uy |] (runOf Z80Table.cb 0x79)
  let BIT7_D =
    mkOp "BIT 7,D" [| 0xCBuy; 0x7auy |] (runOf Z80Table.cb 0x7A)
  let BIT7_E =
    mkOp "BIT 7,E" [| 0xCBuy; 0x7buy |] (runOf Z80Table.cb 0x7B)
  let BIT7_H =
    mkOp "BIT 7,H" [| 0xCBuy; 0x7cuy |] (runOf Z80Table.cb 0x7C)
  let BIT7_L =
    mkOp "BIT 7,L" [| 0xCBuy; 0x7duy |] (runOf Z80Table.cb 0x7D)
  let BIT7_A =
    mkOp "BIT 7,A" [| 0xCBuy; 0x7fuy |] (runOf Z80Table.cb 0x7F)
  let BIT7_PTR_HL =
    mkOp "BIT 7,(HL)" [| 0xCBuy; 0x7euy |] (runOf Z80Table.cb 0x7E)
  let BIT7_PTR_IXd (d : int) =
    mkOp "BIT 7,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0x7euy |] (runOf Z80Table.dd_cb 0x7E)
  let BIT7_PTR_IYd (d : int) =
    mkOp "BIT 7,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0x7euy |] (runOf Z80Table.fd_cb 0x7E)
  let RES7_B =
    mkOp "RES 7,B" [| 0xCBuy; 0xb8uy |] (runOf Z80Table.cb 0xB8)
  let RES7_C =
    mkOp "RES 7,C" [| 0xCBuy; 0xb9uy |] (runOf Z80Table.cb 0xB9)
  let RES7_D =
    mkOp "RES 7,D" [| 0xCBuy; 0xbauy |] (runOf Z80Table.cb 0xBA)
  let RES7_E =
    mkOp "RES 7,E" [| 0xCBuy; 0xbbuy |] (runOf Z80Table.cb 0xBB)
  let RES7_H =
    mkOp "RES 7,H" [| 0xCBuy; 0xbcuy |] (runOf Z80Table.cb 0xBC)
  let RES7_L =
    mkOp "RES 7,L" [| 0xCBuy; 0xbduy |] (runOf Z80Table.cb 0xBD)
  let RES7_A =
    mkOp "RES 7,A" [| 0xCBuy; 0xbfuy |] (runOf Z80Table.cb 0xBF)
  let RES7_PTR_HL =
    mkOp "RES 7,(HL)" [| 0xCBuy; 0xbeuy |] (runOf Z80Table.cb 0xBE)
  let RES7_PTR_IXd (d : int) =
    mkOp "RES 7,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xbeuy |] (runOf Z80Table.dd_cb 0xBE)
  let RES7_PTR_IYd (d : int) =
    mkOp "RES 7,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xbeuy |] (runOf Z80Table.fd_cb 0xBE)
  let SET7_B =
    mkOp "SET 7,B" [| 0xCBuy; 0xf8uy |] (runOf Z80Table.cb 0xF8)
  let SET7_C =
    mkOp "SET 7,C" [| 0xCBuy; 0xf9uy |] (runOf Z80Table.cb 0xF9)
  let SET7_D =
    mkOp "SET 7,D" [| 0xCBuy; 0xfauy |] (runOf Z80Table.cb 0xFA)
  let SET7_E =
    mkOp "SET 7,E" [| 0xCBuy; 0xfbuy |] (runOf Z80Table.cb 0xFB)
  let SET7_H =
    mkOp "SET 7,H" [| 0xCBuy; 0xfcuy |] (runOf Z80Table.cb 0xFC)
  let SET7_L =
    mkOp "SET 7,L" [| 0xCBuy; 0xfduy |] (runOf Z80Table.cb 0xFD)
  let SET7_A =
    mkOp "SET 7,A" [| 0xCBuy; 0xffuy |] (runOf Z80Table.cb 0xFF)
  let SET7_PTR_HL =
    mkOp "SET 7,(HL)" [| 0xCBuy; 0xfeuy |] (runOf Z80Table.cb 0xFE)
  let SET7_PTR_IXd (d : int) =
    mkOp "SET 7,(IX+d)" [| 0xdduy; 0xcbuy; byte (d &&& 0xFF); 0xfeuy |] (runOf Z80Table.dd_cb 0xFE)
  let SET7_PTR_IYd (d : int) =
    mkOp "SET 7,(IY+d)" [| 0xfduy; 0xcbuy; byte (d &&& 0xFF); 0xfeuy |] (runOf Z80Table.fd_cb 0xFE)
  let JP_nn (nn : int) =
    mkOp "JP nn" [| 0xc3uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xC3)
  let JP_NZ (nn : int) =
    mkOp "JP NZ,nn" [| 0xc2uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xC2)
  let JP_Z (nn : int) =
    mkOp "JP Z,nn" [| 0xcauy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xCA)
  let JP_NC (nn : int) =
    mkOp "JP NC,nn" [| 0xd2uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xD2)
  let JP_C (nn : int) =
    mkOp "JP C,nn" [| 0xdauy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xDA)
  let JP_PO (nn : int) =
    mkOp "JP PO,nn" [| 0xe2uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xE2)
  let JP_PE (nn : int) =
    mkOp "JP PE,nn" [| 0xeauy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xEA)
  let JP_P (nn : int) =
    mkOp "JP P,nn" [| 0xf2uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xF2)
  let JP_M (nn : int) =
    mkOp "JP M,nn" [| 0xfauy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xFA)
  let JP_HL =
    mkOp "JP (HL)" [| 0xE9uy |] (runOf Z80Table.main 0xE9)
  let JP_IX =
    mkOp "JP (IX)" [| 0xDDuy; 0xE9uy |] (runOf Z80Table.dd 0xE9)
  let JP_IY =
    mkOp "JP (IY)" [| 0xFDuy; 0xE9uy |] (runOf Z80Table.fd 0xE9)
  let JR_e (e : int) =
    mkOp "JR e" [| 0x18uy; byte (e &&& 0xFF) |] (runOf Z80Table.main 0x18)
  let JR_NZ (e : int) =
    mkOp "JR NZ,e" [| 0x20uy; byte (e &&& 0xFF) |] (runOf Z80Table.main 0x20)
  let JR_Z (e : int) =
    mkOp "JR Z,e" [| 0x28uy; byte (e &&& 0xFF) |] (runOf Z80Table.main 0x28)
  let JR_NC (e : int) =
    mkOp "JR NC,e" [| 0x30uy; byte (e &&& 0xFF) |] (runOf Z80Table.main 0x30)
  let JR_C (e : int) =
    mkOp "JR C,e" [| 0x38uy; byte (e &&& 0xFF) |] (runOf Z80Table.main 0x38)
  let DJNZ_e (e : int) =
    mkOp "DJNZ e" [| 0x10uy; byte (e &&& 0xFF) |] (runOf Z80Table.main 0x10)
  let CALL_nn (nn : int) =
    mkOp "CALL nn" [| 0xcduy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xCD)
  let CALL_NZ (nn : int) =
    mkOp "CALL NZ,nn" [| 0xc4uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xC4)
  let CALL_Z (nn : int) =
    mkOp "CALL Z,nn" [| 0xccuy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xCC)
  let CALL_NC (nn : int) =
    mkOp "CALL NC,nn" [| 0xd4uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xD4)
  let CALL_C (nn : int) =
    mkOp "CALL C,nn" [| 0xdcuy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xDC)
  let CALL_PO (nn : int) =
    mkOp "CALL PO,nn" [| 0xe4uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xE4)
  let CALL_PE (nn : int) =
    mkOp "CALL PE,nn" [| 0xecuy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xEC)
  let CALL_P (nn : int) =
    mkOp "CALL P,nn" [| 0xf4uy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xF4)
  let CALL_M (nn : int) =
    mkOp "CALL M,nn" [| 0xfcuy; byte (nn &&& 0xFF); byte ((nn >>> 8) &&& 0xFF) |] (runOf Z80Table.main 0xFC)
  let RET =
    mkOp "RET" [| 0xC9uy |] (runOf Z80Table.main 0xC9)
  let RET_NZ =
    mkOp "RET NZ" [| 0xc0uy |] (runOf Z80Table.main 0xC0)
  let RET_Z =
    mkOp "RET Z" [| 0xc8uy |] (runOf Z80Table.main 0xC8)
  let RET_NC =
    mkOp "RET NC" [| 0xd0uy |] (runOf Z80Table.main 0xD0)
  let RET_C =
    mkOp "RET C" [| 0xd8uy |] (runOf Z80Table.main 0xD8)
  let RET_PO =
    mkOp "RET PO" [| 0xe0uy |] (runOf Z80Table.main 0xE0)
  let RET_PE =
    mkOp "RET PE" [| 0xe8uy |] (runOf Z80Table.main 0xE8)
  let RET_P =
    mkOp "RET P" [| 0xf0uy |] (runOf Z80Table.main 0xF0)
  let RET_M =
    mkOp "RET M" [| 0xf8uy |] (runOf Z80Table.main 0xF8)
  let RETI =
    mkOp "RETI" [| 0xEDuy; 0x4Duy |] (runOf Z80Table.ed 0x4D)
  let RETN =
    mkOp "RETN" [| 0xEDuy; 0x45uy |] (runOf Z80Table.ed 0x45)
  let RST_00 =
    mkOp "RST 0x00" [| 0xc7uy |] (runOf Z80Table.main 0xC7)
  let RST_08 =
    mkOp "RST 0x08" [| 0xcfuy |] (runOf Z80Table.main 0xCF)
  let RST_10 =
    mkOp "RST 0x10" [| 0xd7uy |] (runOf Z80Table.main 0xD7)
  let RST_18 =
    mkOp "RST 0x18" [| 0xdfuy |] (runOf Z80Table.main 0xDF)
  let RST_20 =
    mkOp "RST 0x20" [| 0xe7uy |] (runOf Z80Table.main 0xE7)
  let RST_28 =
    mkOp "RST 0x28" [| 0xefuy |] (runOf Z80Table.main 0xEF)
  let RST_30 =
    mkOp "RST 0x30" [| 0xf7uy |] (runOf Z80Table.main 0xF7)
  let RST_38 =
    mkOp "RST 0x38" [| 0xffuy |] (runOf Z80Table.main 0xFF)
  let NOP =
    mkOp "NOP" [| 0x00uy |] (runOf Z80Table.main 0x00)
  let HALT =
    mkOp "HALT" [| 0x76uy |] (runOf Z80Table.main 0x76)
  let DI =
    mkOp "DI" [| 0xF3uy |] (runOf Z80Table.main 0xF3)
  let EI =
    mkOp "EI" [| 0xFBuy |] (runOf Z80Table.main 0xFB)
  let SCF =
    mkOp "SCF" [| 0x37uy |] (runOf Z80Table.main 0x37)
  let CCF =
    mkOp "CCF" [| 0x3Fuy |] (runOf Z80Table.main 0x3F)
  let CPL =
    mkOp "CPL" [| 0x2Fuy |] (runOf Z80Table.main 0x2F)
  let DAA =
    mkOp "DAA" [| 0x27uy |] (runOf Z80Table.main 0x27)
  let NEG =
    mkOp "NEG" [| 0xEDuy; 0x44uy |] (runOf Z80Table.ed 0x44)
  let EX_DE_HL =
    mkOp "EX DE,HL" [| 0xEBuy |] (runOf Z80Table.main 0xEB)
  let EX_AF_AF =
    mkOp "EX AF,AF'" [| 0x08uy |] (runOf Z80Table.main 0x08)
  let EXX =
    mkOp "EXX" [| 0xD9uy |] (runOf Z80Table.main 0xD9)
  let RLCA =
    mkOp "RLCA" [| 0x07uy |] (runOf Z80Table.main 0x07)
  let RRCA =
    mkOp "RRCA" [| 0x0Fuy |] (runOf Z80Table.main 0x0F)
  let RLA =
    mkOp "RLA" [| 0x17uy |] (runOf Z80Table.main 0x17)
  let RRA =
    mkOp "RRA" [| 0x1Fuy |] (runOf Z80Table.main 0x1F)
  let IM_0 =
    mkOp "IM 0" [| 0xEDuy; 0x46uy |] (runOf Z80Table.ed 0x46)
  let IM_1 =
    mkOp "IM 1" [| 0xEDuy; 0x56uy |] (runOf Z80Table.ed 0x56)
  let IM_2 =
    mkOp "IM 2" [| 0xEDuy; 0x5Euy |] (runOf Z80Table.ed 0x5E)
  let RRD =
    mkOp "RRD" [| 0xEDuy; 0x67uy |] (runOf Z80Table.ed 0x67)
  let RLD =
    mkOp "RLD" [| 0xEDuy; 0x6Fuy |] (runOf Z80Table.ed 0x6F)
  let LDI =
    mkOp "LDI" [| 0xEDuy; 0xA0uy |] (runOf Z80Table.ed 0xA0)
  let LDD =
    mkOp "LDD" [| 0xEDuy; 0xA8uy |] (runOf Z80Table.ed 0xA8)
  let LDIR =
    mkOp "LDIR" [| 0xEDuy; 0xB0uy |] (runOf Z80Table.ed 0xB0)
  let LDDR =
    mkOp "LDDR" [| 0xEDuy; 0xB8uy |] (runOf Z80Table.ed 0xB8)
  let CPI =
    mkOp "CPI" [| 0xEDuy; 0xA1uy |] (runOf Z80Table.ed 0xA1)
  let CPD =
    mkOp "CPD" [| 0xEDuy; 0xA9uy |] (runOf Z80Table.ed 0xA9)
  let CPIR =
    mkOp "CPIR" [| 0xEDuy; 0xB1uy |] (runOf Z80Table.ed 0xB1)
  let CPDR =
    mkOp "CPDR" [| 0xEDuy; 0xB9uy |] (runOf Z80Table.ed 0xB9)
  let EX_SP_HL =
    mkOp "EX (SP),HL" [| 0xE3uy |] (runOf Z80Table.main 0xE3)
  let EX_SP_IX =
    mkOp "EX (SP),IX" [| 0xDDuy; 0xE3uy |] (runOf Z80Table.dd 0xE3)
  let EX_SP_IY =
    mkOp "EX (SP),IY" [| 0xFDuy; 0xE3uy |] (runOf Z80Table.fd 0xE3)
  let IN_A_n (n : int) =
    mkOp "IN A,(n)" [| 0xdbuy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xDB)
  let OUT_n_A (n : int) =
    mkOp "OUT (n),A" [| 0xd3uy; byte (n &&& 0xFF) |] (runOf Z80Table.main 0xD3)
  let IN_B_C =
    mkOp "IN B,(C)" [| 0xEDuy; 0x40uy |] (runOf Z80Table.ed 0x40)
  let OUT_C_B =
    mkOp "OUT (C),B" [| 0xEDuy; 0x41uy |] (runOf Z80Table.ed 0x41)
  let IN_C_C =
    mkOp "IN C,(C)" [| 0xEDuy; 0x48uy |] (runOf Z80Table.ed 0x48)
  let OUT_C_C =
    mkOp "OUT (C),C" [| 0xEDuy; 0x49uy |] (runOf Z80Table.ed 0x49)
  let IN_D_C =
    mkOp "IN D,(C)" [| 0xEDuy; 0x50uy |] (runOf Z80Table.ed 0x50)
  let OUT_C_D =
    mkOp "OUT (C),D" [| 0xEDuy; 0x51uy |] (runOf Z80Table.ed 0x51)
  let IN_E_C =
    mkOp "IN E,(C)" [| 0xEDuy; 0x58uy |] (runOf Z80Table.ed 0x58)
  let OUT_C_E =
    mkOp "OUT (C),E" [| 0xEDuy; 0x59uy |] (runOf Z80Table.ed 0x59)
  let IN_H_C =
    mkOp "IN H,(C)" [| 0xEDuy; 0x60uy |] (runOf Z80Table.ed 0x60)
  let OUT_C_H =
    mkOp "OUT (C),H" [| 0xEDuy; 0x61uy |] (runOf Z80Table.ed 0x61)
  let IN_L_C =
    mkOp "IN L,(C)" [| 0xEDuy; 0x68uy |] (runOf Z80Table.ed 0x68)
  let OUT_C_L =
    mkOp "OUT (C),L" [| 0xEDuy; 0x69uy |] (runOf Z80Table.ed 0x69)
  let IN_A_C =
    mkOp "IN A,(C)" [| 0xEDuy; 0x78uy |] (runOf Z80Table.ed 0x78)
  let OUT_C_A =
    mkOp "OUT (C),A" [| 0xEDuy; 0x79uy |] (runOf Z80Table.ed 0x79)
  let IN_PTR_C =
    mkOp "IN (C)" [| 0xEDuy; 0x70uy |] (runOf Z80Table.ed 0x70)
  let OUT_C_0 =
    mkOp "OUT (C),0" [| 0xEDuy; 0x71uy |] (runOf Z80Table.ed 0x71)

  /// Concrete instances for the per-op oracle test:
  /// (name, op, setup kind).
  let allOps : (string * Z80Op * string) list =
    [
    ("LD_B_B", LD_B_B, "default")
    ("LD_B_C", LD_B_C, "default")
    ("LD_B_D", LD_B_D, "default")
    ("LD_B_E", LD_B_E, "default")
    ("LD_B_H", LD_B_H, "default")
    ("LD_B_L", LD_B_L, "default")
    ("LD_B_A", LD_B_A, "default")
    ("LD_C_B", LD_C_B, "default")
    ("LD_C_C", LD_C_C, "default")
    ("LD_C_D", LD_C_D, "default")
    ("LD_C_E", LD_C_E, "default")
    ("LD_C_H", LD_C_H, "default")
    ("LD_C_L", LD_C_L, "default")
    ("LD_C_A", LD_C_A, "default")
    ("LD_D_B", LD_D_B, "default")
    ("LD_D_C", LD_D_C, "default")
    ("LD_D_D", LD_D_D, "default")
    ("LD_D_E", LD_D_E, "default")
    ("LD_D_H", LD_D_H, "default")
    ("LD_D_L", LD_D_L, "default")
    ("LD_D_A", LD_D_A, "default")
    ("LD_E_B", LD_E_B, "default")
    ("LD_E_C", LD_E_C, "default")
    ("LD_E_D", LD_E_D, "default")
    ("LD_E_E", LD_E_E, "default")
    ("LD_E_H", LD_E_H, "default")
    ("LD_E_L", LD_E_L, "default")
    ("LD_E_A", LD_E_A, "default")
    ("LD_H_B", LD_H_B, "default")
    ("LD_H_C", LD_H_C, "default")
    ("LD_H_D", LD_H_D, "default")
    ("LD_H_E", LD_H_E, "default")
    ("LD_H_H", LD_H_H, "default")
    ("LD_H_L", LD_H_L, "default")
    ("LD_H_A", LD_H_A, "default")
    ("LD_L_B", LD_L_B, "default")
    ("LD_L_C", LD_L_C, "default")
    ("LD_L_D", LD_L_D, "default")
    ("LD_L_E", LD_L_E, "default")
    ("LD_L_H", LD_L_H, "default")
    ("LD_L_L", LD_L_L, "default")
    ("LD_L_A", LD_L_A, "default")
    ("LD_A_B", LD_A_B, "default")
    ("LD_A_C", LD_A_C, "default")
    ("LD_A_D", LD_A_D, "default")
    ("LD_A_E", LD_A_E, "default")
    ("LD_A_H", LD_A_H, "default")
    ("LD_A_L", LD_A_L, "default")
    ("LD_A_A", LD_A_A, "default")
    ("LD_B_PTR_HL", LD_B_PTR_HL, "hl")
    ("LD_C_PTR_HL", LD_C_PTR_HL, "hl")
    ("LD_D_PTR_HL", LD_D_PTR_HL, "hl")
    ("LD_E_PTR_HL", LD_E_PTR_HL, "hl")
    ("LD_H_PTR_HL", LD_H_PTR_HL, "hl")
    ("LD_L_PTR_HL", LD_L_PTR_HL, "hl")
    ("LD_A_PTR_HL", LD_A_PTR_HL, "hl")
    ("LD_PTR_HL_B", LD_PTR_HL_B, "hl")
    ("LD_PTR_HL_C", LD_PTR_HL_C, "hl")
    ("LD_PTR_HL_D", LD_PTR_HL_D, "hl")
    ("LD_PTR_HL_E", LD_PTR_HL_E, "hl")
    ("LD_PTR_HL_H", LD_PTR_HL_H, "hl")
    ("LD_PTR_HL_L", LD_PTR_HL_L, "hl")
    ("LD_PTR_HL_A", LD_PTR_HL_A, "hl")
    ("LD_B", LD_B 0x55, "default")
    ("LD_C", LD_C 0x55, "default")
    ("LD_D", LD_D 0x55, "default")
    ("LD_E", LD_E 0x55, "default")
    ("LD_H", LD_H 0x55, "default")
    ("LD_L", LD_L 0x55, "default")
    ("LD_A", LD_A 0x55, "default")
    ("LD_A_ptr", LD_A_ptr 0x1234, "nn")
    ("LD_ptr_A", LD_ptr_A 0x1234, "nn")
    ("LD_A_BC", LD_A_BC, "hl")
    ("LD_A_DE", LD_A_DE, "hl")
    ("LD_BC_A", LD_BC_A, "hl")
    ("LD_DE_A", LD_DE_A, "hl")
    ("LD_BC", LD_BC 0x1234, "default")
    ("LD_DE", LD_DE 0x1234, "default")
    ("LD_HL", LD_HL 0x1234, "default")
    ("LD_SP", LD_SP 0x1234, "default")
    ("LD_IX", LD_IX 0x1234, "default")
    ("LD_IY", LD_IY 0x1234, "default")
    ("LD_HL_ptr", LD_HL_ptr 0x1234, "nn")
    ("LD_ptr_HL", LD_ptr_HL 0x1234, "nn")
    ("LD_IX_ptr", LD_IX_ptr 0x1234, "nn")
    ("LD_ptr_IX", LD_ptr_IX 0x1234, "nn")
    ("LD_IY_ptr", LD_IY_ptr 0x1234, "nn")
    ("LD_ptr_IY", LD_ptr_IY 0x1234, "nn")
    ("LD_ptr_BC", LD_ptr_BC 0x1234, "nn")
    ("LD_BC_ptr", LD_BC_ptr 0x1234, "nn")
    ("LD_ptr_DE", LD_ptr_DE 0x1234, "nn")
    ("LD_DE_ptr", LD_DE_ptr 0x1234, "nn")
    ("LD_ptr_SP", LD_ptr_SP 0x1234, "nn")
    ("LD_SP_ptr", LD_SP_ptr 0x1234, "nn")
    ("LD_SP_HL", LD_SP_HL, "default")
    ("LD_SP_IX", LD_SP_IX, "default")
    ("LD_SP_IY", LD_SP_IY, "default")
    ("LD_A_I", LD_A_I, "default")
    ("LD_A_R", LD_A_R, "default")
    ("LD_I_A", LD_I_A, "default")
    ("LD_R_A", LD_R_A, "default")
    ("LD_B_IXH", LD_B_IXH, "default")
    ("LD_B_IXL", LD_B_IXL, "default")
    ("LD_C_IXH", LD_C_IXH, "default")
    ("LD_C_IXL", LD_C_IXL, "default")
    ("LD_D_IXH", LD_D_IXH, "default")
    ("LD_D_IXL", LD_D_IXL, "default")
    ("LD_E_IXH", LD_E_IXH, "default")
    ("LD_E_IXL", LD_E_IXL, "default")
    ("LD_IXH_B", LD_IXH_B, "default")
    ("LD_IXH_C", LD_IXH_C, "default")
    ("LD_IXH_D", LD_IXH_D, "default")
    ("LD_IXH_E", LD_IXH_E, "default")
    ("LD_IXH_A", LD_IXH_A, "default")
    ("LD_IXL_B", LD_IXL_B, "default")
    ("LD_IXL_C", LD_IXL_C, "default")
    ("LD_IXL_D", LD_IXL_D, "default")
    ("LD_IXL_E", LD_IXL_E, "default")
    ("LD_IXL_A", LD_IXL_A, "default")
    ("LD_IXH_n", LD_IXH_n 0x55, "default")
    ("LD_IXL_n", LD_IXL_n 0x55, "default")
    ("LD_B_IXd", LD_B_IXd 0x55, "ixd")
    ("LD_C_IXd", LD_C_IXd 0x55, "ixd")
    ("LD_D_IXd", LD_D_IXd 0x55, "ixd")
    ("LD_E_IXd", LD_E_IXd 0x55, "ixd")
    ("LD_H_IXd", LD_H_IXd 0x55, "ixd")
    ("LD_L_IXd", LD_L_IXd 0x55, "ixd")
    ("LD_A_IXd", LD_A_IXd 0x55, "ixd")
    ("LD_B_IYd", LD_B_IYd 0x55, "iyd")
    ("LD_C_IYd", LD_C_IYd 0x55, "iyd")
    ("LD_D_IYd", LD_D_IYd 0x55, "iyd")
    ("LD_E_IYd", LD_E_IYd 0x55, "iyd")
    ("LD_H_IYd", LD_H_IYd 0x55, "iyd")
    ("LD_L_IYd", LD_L_IYd 0x55, "iyd")
    ("LD_A_IYd", LD_A_IYd 0x55, "iyd")
    ("LD_IXd_B", LD_IXd_B 0x55, "ixd")
    ("LD_IXd_C", LD_IXd_C 0x55, "ixd")
    ("LD_IXd_D", LD_IXd_D 0x55, "ixd")
    ("LD_IXd_E", LD_IXd_E 0x55, "ixd")
    ("LD_IXd_H", LD_IXd_H 0x55, "ixd")
    ("LD_IXd_L", LD_IXd_L 0x55, "ixd")
    ("LD_IXd_A", LD_IXd_A 0x55, "ixd")
    ("LD_IYd_B", LD_IYd_B 0x55, "iyd")
    ("LD_IYd_C", LD_IYd_C 0x55, "iyd")
    ("LD_IYd_D", LD_IYd_D 0x55, "iyd")
    ("LD_IYd_E", LD_IYd_E 0x55, "iyd")
    ("LD_IYd_H", LD_IYd_H 0x55, "iyd")
    ("LD_IYd_L", LD_IYd_L 0x55, "iyd")
    ("LD_IYd_A", LD_IYd_A 0x55, "iyd")
    ("ADD_A_B", ADD_A_B, "default")
    ("ADD_A_C", ADD_A_C, "default")
    ("ADD_A_D", ADD_A_D, "default")
    ("ADD_A_E", ADD_A_E, "default")
    ("ADD_A_H", ADD_A_H, "default")
    ("ADD_A_L", ADD_A_L, "default")
    ("ADD_A_A", ADD_A_A, "default")
    ("ADD_A_PTR_HL", ADD_A_PTR_HL, "hl")
    ("ADD_A_n", ADD_A_n 0x55, "default")
    ("ADD_A_IXd", ADD_A_IXd 0x55, "ixd")
    ("ADD_A_IYd", ADD_A_IYd 0x55, "iyd")
    ("ADC_A_B", ADC_A_B, "default")
    ("ADC_A_C", ADC_A_C, "default")
    ("ADC_A_D", ADC_A_D, "default")
    ("ADC_A_E", ADC_A_E, "default")
    ("ADC_A_H", ADC_A_H, "default")
    ("ADC_A_L", ADC_A_L, "default")
    ("ADC_A_A", ADC_A_A, "default")
    ("ADC_A_PTR_HL", ADC_A_PTR_HL, "hl")
    ("ADC_A_n", ADC_A_n 0x55, "default")
    ("ADC_A_IXd", ADC_A_IXd 0x55, "ixd")
    ("ADC_A_IYd", ADC_A_IYd 0x55, "iyd")
    ("SUB_A_B", SUB_A_B, "default")
    ("SUB_A_C", SUB_A_C, "default")
    ("SUB_A_D", SUB_A_D, "default")
    ("SUB_A_E", SUB_A_E, "default")
    ("SUB_A_H", SUB_A_H, "default")
    ("SUB_A_L", SUB_A_L, "default")
    ("SUB_A_A", SUB_A_A, "default")
    ("SUB_A_PTR_HL", SUB_A_PTR_HL, "hl")
    ("SUB_A_n", SUB_A_n 0x55, "default")
    ("SUB_A_IXd", SUB_A_IXd 0x55, "ixd")
    ("SUB_A_IYd", SUB_A_IYd 0x55, "iyd")
    ("SBC_A_B", SBC_A_B, "default")
    ("SBC_A_C", SBC_A_C, "default")
    ("SBC_A_D", SBC_A_D, "default")
    ("SBC_A_E", SBC_A_E, "default")
    ("SBC_A_H", SBC_A_H, "default")
    ("SBC_A_L", SBC_A_L, "default")
    ("SBC_A_A", SBC_A_A, "default")
    ("SBC_A_PTR_HL", SBC_A_PTR_HL, "hl")
    ("SBC_A_n", SBC_A_n 0x55, "default")
    ("SBC_A_IXd", SBC_A_IXd 0x55, "ixd")
    ("SBC_A_IYd", SBC_A_IYd 0x55, "iyd")
    ("AND_A_B", AND_A_B, "default")
    ("AND_A_C", AND_A_C, "default")
    ("AND_A_D", AND_A_D, "default")
    ("AND_A_E", AND_A_E, "default")
    ("AND_A_H", AND_A_H, "default")
    ("AND_A_L", AND_A_L, "default")
    ("AND_A_A", AND_A_A, "default")
    ("AND_A_PTR_HL", AND_A_PTR_HL, "hl")
    ("AND_A_n", AND_A_n 0x55, "default")
    ("AND_A_IXd", AND_A_IXd 0x55, "ixd")
    ("AND_A_IYd", AND_A_IYd 0x55, "iyd")
    ("XOR_A_B", XOR_A_B, "default")
    ("XOR_A_C", XOR_A_C, "default")
    ("XOR_A_D", XOR_A_D, "default")
    ("XOR_A_E", XOR_A_E, "default")
    ("XOR_A_H", XOR_A_H, "default")
    ("XOR_A_L", XOR_A_L, "default")
    ("XOR_A_A", XOR_A_A, "default")
    ("XOR_A_PTR_HL", XOR_A_PTR_HL, "hl")
    ("XOR_A_n", XOR_A_n 0x55, "default")
    ("XOR_A_IXd", XOR_A_IXd 0x55, "ixd")
    ("XOR_A_IYd", XOR_A_IYd 0x55, "iyd")
    ("OR_A_B", OR_A_B, "default")
    ("OR_A_C", OR_A_C, "default")
    ("OR_A_D", OR_A_D, "default")
    ("OR_A_E", OR_A_E, "default")
    ("OR_A_H", OR_A_H, "default")
    ("OR_A_L", OR_A_L, "default")
    ("OR_A_A", OR_A_A, "default")
    ("OR_A_PTR_HL", OR_A_PTR_HL, "hl")
    ("OR_A_n", OR_A_n 0x55, "default")
    ("OR_A_IXd", OR_A_IXd 0x55, "ixd")
    ("OR_A_IYd", OR_A_IYd 0x55, "iyd")
    ("CP_A_B", CP_A_B, "default")
    ("CP_A_C", CP_A_C, "default")
    ("CP_A_D", CP_A_D, "default")
    ("CP_A_E", CP_A_E, "default")
    ("CP_A_H", CP_A_H, "default")
    ("CP_A_L", CP_A_L, "default")
    ("CP_A_A", CP_A_A, "default")
    ("CP_A_PTR_HL", CP_A_PTR_HL, "hl")
    ("CP_A_n", CP_A_n 0x55, "default")
    ("CP_A_IXd", CP_A_IXd 0x55, "ixd")
    ("CP_A_IYd", CP_A_IYd 0x55, "iyd")
    ("ADD_HL_BC", ADD_HL_BC, "default")
    ("ADC_HL_BC", ADC_HL_BC, "default")
    ("SBC_HL_BC", SBC_HL_BC, "default")
    ("ADD_HL_DE", ADD_HL_DE, "default")
    ("ADC_HL_DE", ADC_HL_DE, "default")
    ("SBC_HL_DE", SBC_HL_DE, "default")
    ("ADD_HL_HL", ADD_HL_HL, "default")
    ("ADC_HL_HL", ADC_HL_HL, "default")
    ("SBC_HL_HL", SBC_HL_HL, "default")
    ("ADD_HL_SP", ADD_HL_SP, "default")
    ("ADC_HL_SP", ADC_HL_SP, "default")
    ("SBC_HL_SP", SBC_HL_SP, "default")
    ("ADD_IX_BC", ADD_IX_BC, "default")
    ("ADD_IY_BC", ADD_IY_BC, "default")
    ("ADD_IX_DE", ADD_IX_DE, "default")
    ("ADD_IY_DE", ADD_IY_DE, "default")
    ("ADD_IX_HL", ADD_IX_HL, "default")
    ("ADD_IY_HL", ADD_IY_HL, "default")
    ("ADD_IX_SP", ADD_IX_SP, "default")
    ("ADD_IY_SP", ADD_IY_SP, "default")
    ("INC_B", INC_B, "default")
    ("DEC_B", DEC_B, "default")
    ("INC_C", INC_C, "default")
    ("DEC_C", DEC_C, "default")
    ("INC_D", INC_D, "default")
    ("DEC_D", DEC_D, "default")
    ("INC_E", INC_E, "default")
    ("DEC_E", DEC_E, "default")
    ("INC_H", INC_H, "default")
    ("DEC_H", DEC_H, "default")
    ("INC_L", INC_L, "default")
    ("DEC_L", DEC_L, "default")
    ("INC_A", INC_A, "default")
    ("DEC_A", DEC_A, "default")
    ("INC_PTR_HL", INC_PTR_HL, "hl")
    ("DEC_PTR_HL", DEC_PTR_HL, "hl")
    ("INC_PTR_IXd", INC_PTR_IXd 0x55, "ixd")
    ("DEC_PTR_IXd", DEC_PTR_IXd 0x55, "ixd")
    ("LD_PTR_IXd_n", LD_PTR_IXd_n 0x02 0x55, "ixd")
    ("INC_BC", INC_BC, "default")
    ("DEC_BC", DEC_BC, "default")
    ("INC_DE", INC_DE, "default")
    ("DEC_DE", DEC_DE, "default")
    ("INC_HL", INC_HL, "default")
    ("DEC_HL", DEC_HL, "default")
    ("INC_SP", INC_SP, "default")
    ("DEC_SP", DEC_SP, "default")
    ("INC_IX", INC_IX, "default")
    ("DEC_IX", DEC_IX, "default")
    ("INC_IXH", INC_IXH, "default")
    ("DEC_IXH", DEC_IXH, "default")
    ("INC_IXL", INC_IXL, "default")
    ("DEC_IXL", DEC_IXL, "default")
    ("PUSH_BC", PUSH_BC, "sp")
    ("POP_BC", POP_BC, "sp")
    ("PUSH_DE", PUSH_DE, "sp")
    ("POP_DE", POP_DE, "sp")
    ("PUSH_HL", PUSH_HL, "sp")
    ("POP_HL", POP_HL, "sp")
    ("PUSH_AF", PUSH_AF, "sp")
    ("POP_AF", POP_AF, "sp")
    ("PUSH_IX", PUSH_IX, "sp")
    ("POP_IX", POP_IX, "sp")
    ("RLC_B", RLC_B, "default")
    ("RLC_C", RLC_C, "default")
    ("RLC_D", RLC_D, "default")
    ("RLC_E", RLC_E, "default")
    ("RLC_H", RLC_H, "default")
    ("RLC_L", RLC_L, "default")
    ("RLC_A", RLC_A, "default")
    ("RLC_PTR_HL", RLC_PTR_HL, "hl")
    ("RLC_PTR_IXd", RLC_PTR_IXd 0x55, "ixd")
    ("RLC_PTR_IYd", RLC_PTR_IYd 0x55, "iyd")
    ("RRC_B", RRC_B, "default")
    ("RRC_C", RRC_C, "default")
    ("RRC_D", RRC_D, "default")
    ("RRC_E", RRC_E, "default")
    ("RRC_H", RRC_H, "default")
    ("RRC_L", RRC_L, "default")
    ("RRC_A", RRC_A, "default")
    ("RRC_PTR_HL", RRC_PTR_HL, "hl")
    ("RRC_PTR_IXd", RRC_PTR_IXd 0x55, "ixd")
    ("RRC_PTR_IYd", RRC_PTR_IYd 0x55, "iyd")
    ("RL_B", RL_B, "default")
    ("RL_C", RL_C, "default")
    ("RL_D", RL_D, "default")
    ("RL_E", RL_E, "default")
    ("RL_H", RL_H, "default")
    ("RL_L", RL_L, "default")
    ("RL_A", RL_A, "default")
    ("RL_PTR_HL", RL_PTR_HL, "hl")
    ("RL_PTR_IXd", RL_PTR_IXd 0x55, "ixd")
    ("RL_PTR_IYd", RL_PTR_IYd 0x55, "iyd")
    ("RR_B", RR_B, "default")
    ("RR_C", RR_C, "default")
    ("RR_D", RR_D, "default")
    ("RR_E", RR_E, "default")
    ("RR_H", RR_H, "default")
    ("RR_L", RR_L, "default")
    ("RR_A", RR_A, "default")
    ("RR_PTR_HL", RR_PTR_HL, "hl")
    ("RR_PTR_IXd", RR_PTR_IXd 0x55, "ixd")
    ("RR_PTR_IYd", RR_PTR_IYd 0x55, "iyd")
    ("SLA_B", SLA_B, "default")
    ("SLA_C", SLA_C, "default")
    ("SLA_D", SLA_D, "default")
    ("SLA_E", SLA_E, "default")
    ("SLA_H", SLA_H, "default")
    ("SLA_L", SLA_L, "default")
    ("SLA_A", SLA_A, "default")
    ("SLA_PTR_HL", SLA_PTR_HL, "hl")
    ("SLA_PTR_IXd", SLA_PTR_IXd 0x55, "ixd")
    ("SLA_PTR_IYd", SLA_PTR_IYd 0x55, "iyd")
    ("SRA_B", SRA_B, "default")
    ("SRA_C", SRA_C, "default")
    ("SRA_D", SRA_D, "default")
    ("SRA_E", SRA_E, "default")
    ("SRA_H", SRA_H, "default")
    ("SRA_L", SRA_L, "default")
    ("SRA_A", SRA_A, "default")
    ("SRA_PTR_HL", SRA_PTR_HL, "hl")
    ("SRA_PTR_IXd", SRA_PTR_IXd 0x55, "ixd")
    ("SRA_PTR_IYd", SRA_PTR_IYd 0x55, "iyd")
    ("SRL_B", SRL_B, "default")
    ("SRL_C", SRL_C, "default")
    ("SRL_D", SRL_D, "default")
    ("SRL_E", SRL_E, "default")
    ("SRL_H", SRL_H, "default")
    ("SRL_L", SRL_L, "default")
    ("SRL_A", SRL_A, "default")
    ("SRL_PTR_HL", SRL_PTR_HL, "hl")
    ("SRL_PTR_IXd", SRL_PTR_IXd 0x55, "ixd")
    ("SRL_PTR_IYd", SRL_PTR_IYd 0x55, "iyd")
    ("BIT0_B", BIT0_B, "default")
    ("BIT0_C", BIT0_C, "default")
    ("BIT0_D", BIT0_D, "default")
    ("BIT0_E", BIT0_E, "default")
    ("BIT0_H", BIT0_H, "default")
    ("BIT0_L", BIT0_L, "default")
    ("BIT0_A", BIT0_A, "default")
    ("BIT0_PTR_HL", BIT0_PTR_HL, "hl")
    ("BIT0_PTR_IXd", BIT0_PTR_IXd 0x55, "ixd")
    ("BIT0_PTR_IYd", BIT0_PTR_IYd 0x55, "iyd")
    ("RES0_B", RES0_B, "default")
    ("RES0_C", RES0_C, "default")
    ("RES0_D", RES0_D, "default")
    ("RES0_E", RES0_E, "default")
    ("RES0_H", RES0_H, "default")
    ("RES0_L", RES0_L, "default")
    ("RES0_A", RES0_A, "default")
    ("RES0_PTR_HL", RES0_PTR_HL, "hl")
    ("RES0_PTR_IXd", RES0_PTR_IXd 0x55, "ixd")
    ("RES0_PTR_IYd", RES0_PTR_IYd 0x55, "iyd")
    ("SET0_B", SET0_B, "default")
    ("SET0_C", SET0_C, "default")
    ("SET0_D", SET0_D, "default")
    ("SET0_E", SET0_E, "default")
    ("SET0_H", SET0_H, "default")
    ("SET0_L", SET0_L, "default")
    ("SET0_A", SET0_A, "default")
    ("SET0_PTR_HL", SET0_PTR_HL, "hl")
    ("SET0_PTR_IXd", SET0_PTR_IXd 0x55, "ixd")
    ("SET0_PTR_IYd", SET0_PTR_IYd 0x55, "iyd")
    ("BIT1_B", BIT1_B, "default")
    ("BIT1_C", BIT1_C, "default")
    ("BIT1_D", BIT1_D, "default")
    ("BIT1_E", BIT1_E, "default")
    ("BIT1_H", BIT1_H, "default")
    ("BIT1_L", BIT1_L, "default")
    ("BIT1_A", BIT1_A, "default")
    ("BIT1_PTR_HL", BIT1_PTR_HL, "hl")
    ("BIT1_PTR_IXd", BIT1_PTR_IXd 0x55, "ixd")
    ("BIT1_PTR_IYd", BIT1_PTR_IYd 0x55, "iyd")
    ("RES1_B", RES1_B, "default")
    ("RES1_C", RES1_C, "default")
    ("RES1_D", RES1_D, "default")
    ("RES1_E", RES1_E, "default")
    ("RES1_H", RES1_H, "default")
    ("RES1_L", RES1_L, "default")
    ("RES1_A", RES1_A, "default")
    ("RES1_PTR_HL", RES1_PTR_HL, "hl")
    ("RES1_PTR_IXd", RES1_PTR_IXd 0x55, "ixd")
    ("RES1_PTR_IYd", RES1_PTR_IYd 0x55, "iyd")
    ("SET1_B", SET1_B, "default")
    ("SET1_C", SET1_C, "default")
    ("SET1_D", SET1_D, "default")
    ("SET1_E", SET1_E, "default")
    ("SET1_H", SET1_H, "default")
    ("SET1_L", SET1_L, "default")
    ("SET1_A", SET1_A, "default")
    ("SET1_PTR_HL", SET1_PTR_HL, "hl")
    ("SET1_PTR_IXd", SET1_PTR_IXd 0x55, "ixd")
    ("SET1_PTR_IYd", SET1_PTR_IYd 0x55, "iyd")
    ("BIT2_B", BIT2_B, "default")
    ("BIT2_C", BIT2_C, "default")
    ("BIT2_D", BIT2_D, "default")
    ("BIT2_E", BIT2_E, "default")
    ("BIT2_H", BIT2_H, "default")
    ("BIT2_L", BIT2_L, "default")
    ("BIT2_A", BIT2_A, "default")
    ("BIT2_PTR_HL", BIT2_PTR_HL, "hl")
    ("BIT2_PTR_IXd", BIT2_PTR_IXd 0x55, "ixd")
    ("BIT2_PTR_IYd", BIT2_PTR_IYd 0x55, "iyd")
    ("RES2_B", RES2_B, "default")
    ("RES2_C", RES2_C, "default")
    ("RES2_D", RES2_D, "default")
    ("RES2_E", RES2_E, "default")
    ("RES2_H", RES2_H, "default")
    ("RES2_L", RES2_L, "default")
    ("RES2_A", RES2_A, "default")
    ("RES2_PTR_HL", RES2_PTR_HL, "hl")
    ("RES2_PTR_IXd", RES2_PTR_IXd 0x55, "ixd")
    ("RES2_PTR_IYd", RES2_PTR_IYd 0x55, "iyd")
    ("SET2_B", SET2_B, "default")
    ("SET2_C", SET2_C, "default")
    ("SET2_D", SET2_D, "default")
    ("SET2_E", SET2_E, "default")
    ("SET2_H", SET2_H, "default")
    ("SET2_L", SET2_L, "default")
    ("SET2_A", SET2_A, "default")
    ("SET2_PTR_HL", SET2_PTR_HL, "hl")
    ("SET2_PTR_IXd", SET2_PTR_IXd 0x55, "ixd")
    ("SET2_PTR_IYd", SET2_PTR_IYd 0x55, "iyd")
    ("BIT3_B", BIT3_B, "default")
    ("BIT3_C", BIT3_C, "default")
    ("BIT3_D", BIT3_D, "default")
    ("BIT3_E", BIT3_E, "default")
    ("BIT3_H", BIT3_H, "default")
    ("BIT3_L", BIT3_L, "default")
    ("BIT3_A", BIT3_A, "default")
    ("BIT3_PTR_HL", BIT3_PTR_HL, "hl")
    ("BIT3_PTR_IXd", BIT3_PTR_IXd 0x55, "ixd")
    ("BIT3_PTR_IYd", BIT3_PTR_IYd 0x55, "iyd")
    ("RES3_B", RES3_B, "default")
    ("RES3_C", RES3_C, "default")
    ("RES3_D", RES3_D, "default")
    ("RES3_E", RES3_E, "default")
    ("RES3_H", RES3_H, "default")
    ("RES3_L", RES3_L, "default")
    ("RES3_A", RES3_A, "default")
    ("RES3_PTR_HL", RES3_PTR_HL, "hl")
    ("RES3_PTR_IXd", RES3_PTR_IXd 0x55, "ixd")
    ("RES3_PTR_IYd", RES3_PTR_IYd 0x55, "iyd")
    ("SET3_B", SET3_B, "default")
    ("SET3_C", SET3_C, "default")
    ("SET3_D", SET3_D, "default")
    ("SET3_E", SET3_E, "default")
    ("SET3_H", SET3_H, "default")
    ("SET3_L", SET3_L, "default")
    ("SET3_A", SET3_A, "default")
    ("SET3_PTR_HL", SET3_PTR_HL, "hl")
    ("SET3_PTR_IXd", SET3_PTR_IXd 0x55, "ixd")
    ("SET3_PTR_IYd", SET3_PTR_IYd 0x55, "iyd")
    ("BIT4_B", BIT4_B, "default")
    ("BIT4_C", BIT4_C, "default")
    ("BIT4_D", BIT4_D, "default")
    ("BIT4_E", BIT4_E, "default")
    ("BIT4_H", BIT4_H, "default")
    ("BIT4_L", BIT4_L, "default")
    ("BIT4_A", BIT4_A, "default")
    ("BIT4_PTR_HL", BIT4_PTR_HL, "hl")
    ("BIT4_PTR_IXd", BIT4_PTR_IXd 0x55, "ixd")
    ("BIT4_PTR_IYd", BIT4_PTR_IYd 0x55, "iyd")
    ("RES4_B", RES4_B, "default")
    ("RES4_C", RES4_C, "default")
    ("RES4_D", RES4_D, "default")
    ("RES4_E", RES4_E, "default")
    ("RES4_H", RES4_H, "default")
    ("RES4_L", RES4_L, "default")
    ("RES4_A", RES4_A, "default")
    ("RES4_PTR_HL", RES4_PTR_HL, "hl")
    ("RES4_PTR_IXd", RES4_PTR_IXd 0x55, "ixd")
    ("RES4_PTR_IYd", RES4_PTR_IYd 0x55, "iyd")
    ("SET4_B", SET4_B, "default")
    ("SET4_C", SET4_C, "default")
    ("SET4_D", SET4_D, "default")
    ("SET4_E", SET4_E, "default")
    ("SET4_H", SET4_H, "default")
    ("SET4_L", SET4_L, "default")
    ("SET4_A", SET4_A, "default")
    ("SET4_PTR_HL", SET4_PTR_HL, "hl")
    ("SET4_PTR_IXd", SET4_PTR_IXd 0x55, "ixd")
    ("SET4_PTR_IYd", SET4_PTR_IYd 0x55, "iyd")
    ("BIT5_B", BIT5_B, "default")
    ("BIT5_C", BIT5_C, "default")
    ("BIT5_D", BIT5_D, "default")
    ("BIT5_E", BIT5_E, "default")
    ("BIT5_H", BIT5_H, "default")
    ("BIT5_L", BIT5_L, "default")
    ("BIT5_A", BIT5_A, "default")
    ("BIT5_PTR_HL", BIT5_PTR_HL, "hl")
    ("BIT5_PTR_IXd", BIT5_PTR_IXd 0x55, "ixd")
    ("BIT5_PTR_IYd", BIT5_PTR_IYd 0x55, "iyd")
    ("RES5_B", RES5_B, "default")
    ("RES5_C", RES5_C, "default")
    ("RES5_D", RES5_D, "default")
    ("RES5_E", RES5_E, "default")
    ("RES5_H", RES5_H, "default")
    ("RES5_L", RES5_L, "default")
    ("RES5_A", RES5_A, "default")
    ("RES5_PTR_HL", RES5_PTR_HL, "hl")
    ("RES5_PTR_IXd", RES5_PTR_IXd 0x55, "ixd")
    ("RES5_PTR_IYd", RES5_PTR_IYd 0x55, "iyd")
    ("SET5_B", SET5_B, "default")
    ("SET5_C", SET5_C, "default")
    ("SET5_D", SET5_D, "default")
    ("SET5_E", SET5_E, "default")
    ("SET5_H", SET5_H, "default")
    ("SET5_L", SET5_L, "default")
    ("SET5_A", SET5_A, "default")
    ("SET5_PTR_HL", SET5_PTR_HL, "hl")
    ("SET5_PTR_IXd", SET5_PTR_IXd 0x55, "ixd")
    ("SET5_PTR_IYd", SET5_PTR_IYd 0x55, "iyd")
    ("BIT6_B", BIT6_B, "default")
    ("BIT6_C", BIT6_C, "default")
    ("BIT6_D", BIT6_D, "default")
    ("BIT6_E", BIT6_E, "default")
    ("BIT6_H", BIT6_H, "default")
    ("BIT6_L", BIT6_L, "default")
    ("BIT6_A", BIT6_A, "default")
    ("BIT6_PTR_HL", BIT6_PTR_HL, "hl")
    ("BIT6_PTR_IXd", BIT6_PTR_IXd 0x55, "ixd")
    ("BIT6_PTR_IYd", BIT6_PTR_IYd 0x55, "iyd")
    ("RES6_B", RES6_B, "default")
    ("RES6_C", RES6_C, "default")
    ("RES6_D", RES6_D, "default")
    ("RES6_E", RES6_E, "default")
    ("RES6_H", RES6_H, "default")
    ("RES6_L", RES6_L, "default")
    ("RES6_A", RES6_A, "default")
    ("RES6_PTR_HL", RES6_PTR_HL, "hl")
    ("RES6_PTR_IXd", RES6_PTR_IXd 0x55, "ixd")
    ("RES6_PTR_IYd", RES6_PTR_IYd 0x55, "iyd")
    ("SET6_B", SET6_B, "default")
    ("SET6_C", SET6_C, "default")
    ("SET6_D", SET6_D, "default")
    ("SET6_E", SET6_E, "default")
    ("SET6_H", SET6_H, "default")
    ("SET6_L", SET6_L, "default")
    ("SET6_A", SET6_A, "default")
    ("SET6_PTR_HL", SET6_PTR_HL, "hl")
    ("SET6_PTR_IXd", SET6_PTR_IXd 0x55, "ixd")
    ("SET6_PTR_IYd", SET6_PTR_IYd 0x55, "iyd")
    ("BIT7_B", BIT7_B, "default")
    ("BIT7_C", BIT7_C, "default")
    ("BIT7_D", BIT7_D, "default")
    ("BIT7_E", BIT7_E, "default")
    ("BIT7_H", BIT7_H, "default")
    ("BIT7_L", BIT7_L, "default")
    ("BIT7_A", BIT7_A, "default")
    ("BIT7_PTR_HL", BIT7_PTR_HL, "hl")
    ("BIT7_PTR_IXd", BIT7_PTR_IXd 0x55, "ixd")
    ("BIT7_PTR_IYd", BIT7_PTR_IYd 0x55, "iyd")
    ("RES7_B", RES7_B, "default")
    ("RES7_C", RES7_C, "default")
    ("RES7_D", RES7_D, "default")
    ("RES7_E", RES7_E, "default")
    ("RES7_H", RES7_H, "default")
    ("RES7_L", RES7_L, "default")
    ("RES7_A", RES7_A, "default")
    ("RES7_PTR_HL", RES7_PTR_HL, "hl")
    ("RES7_PTR_IXd", RES7_PTR_IXd 0x55, "ixd")
    ("RES7_PTR_IYd", RES7_PTR_IYd 0x55, "iyd")
    ("SET7_B", SET7_B, "default")
    ("SET7_C", SET7_C, "default")
    ("SET7_D", SET7_D, "default")
    ("SET7_E", SET7_E, "default")
    ("SET7_H", SET7_H, "default")
    ("SET7_L", SET7_L, "default")
    ("SET7_A", SET7_A, "default")
    ("SET7_PTR_HL", SET7_PTR_HL, "hl")
    ("SET7_PTR_IXd", SET7_PTR_IXd 0x55, "ixd")
    ("SET7_PTR_IYd", SET7_PTR_IYd 0x55, "iyd")
    ("JP_nn", JP_nn 0x8003, "jp")
    ("JP_NZ", JP_NZ 0x8003, "jp")
    ("JP_Z", JP_Z 0x8003, "jp")
    ("JP_NC", JP_NC 0x8003, "jp")
    ("JP_C", JP_C 0x8003, "jp")
    ("JP_PO", JP_PO 0x8003, "jp")
    ("JP_PE", JP_PE 0x8003, "jp")
    ("JP_P", JP_P 0x8003, "jp")
    ("JP_M", JP_M 0x8003, "jp")
    ("JP_HL", JP_HL, "jp")
    ("JP_IX", JP_IX, "jp")
    ("JP_IY", JP_IY, "jp")
    ("JR_e", JR_e 0x00, "jr")
    ("JR_NZ", JR_NZ 0x00, "jr")
    ("JR_Z", JR_Z 0x00, "jr")
    ("JR_NC", JR_NC 0x00, "jr")
    ("JR_C", JR_C 0x00, "jr")
    ("DJNZ_e", DJNZ_e 0x00, "djnz")
    ("CALL_nn", CALL_nn 0x8003, "call")
    ("CALL_NZ", CALL_NZ 0x8003, "call")
    ("CALL_Z", CALL_Z 0x8003, "call")
    ("CALL_NC", CALL_NC 0x8003, "call")
    ("CALL_C", CALL_C 0x8003, "call")
    ("CALL_PO", CALL_PO 0x8003, "call")
    ("CALL_PE", CALL_PE 0x8003, "call")
    ("CALL_P", CALL_P 0x8003, "call")
    ("CALL_M", CALL_M 0x8003, "call")
    ("RET", RET, "ret")
    ("RET_NZ", RET_NZ, "ret")
    ("RET_Z", RET_Z, "ret")
    ("RET_NC", RET_NC, "ret")
    ("RET_C", RET_C, "ret")
    ("RET_PO", RET_PO, "ret")
    ("RET_PE", RET_PE, "ret")
    ("RET_P", RET_P, "ret")
    ("RET_M", RET_M, "ret")
    ("RETI", RETI, "ret")
    ("RETN", RETN, "ret")
    ("RST_00", RST_00, "rst")
    ("RST_08", RST_08, "rst")
    ("RST_10", RST_10, "rst")
    ("RST_18", RST_18, "rst")
    ("RST_20", RST_20, "rst")
    ("RST_28", RST_28, "rst")
    ("RST_30", RST_30, "rst")
    ("RST_38", RST_38, "rst")
    ("NOP", NOP, "default")
    ("HALT", HALT, "halt")
    ("DI", DI, "default")
    ("EI", EI, "default")
    ("SCF", SCF, "default")
    ("CCF", CCF, "default")
    ("CPL", CPL, "default")
    ("DAA", DAA, "default")
    ("NEG", NEG, "default")
    ("EX_DE_HL", EX_DE_HL, "default")
    ("EX_AF_AF", EX_AF_AF, "default")
    ("EXX", EXX, "default")
    ("RLCA", RLCA, "default")
    ("RRCA", RRCA, "default")
    ("RLA", RLA, "default")
    ("RRA", RRA, "default")
    ("IM_0", IM_0, "default")
    ("IM_1", IM_1, "default")
    ("IM_2", IM_2, "default")
    ("RRD", RRD, "hl")
    ("RLD", RLD, "hl")
    ("LDI", LDI, "block")
    ("LDD", LDD, "block")
    ("LDIR", LDIR, "block")
    ("LDDR", LDDR, "block")
    ("CPI", CPI, "block")
    ("CPD", CPD, "block")
    ("CPIR", CPIR, "block")
    ("CPDR", CPDR, "block")
    ("EX_SP_HL", EX_SP_HL, "exsp")
    ("EX_SP_IX", EX_SP_IX, "exsp")
    ("EX_SP_IY", EX_SP_IY, "exsp")
    ("IN_A_n", IN_A_n 0x55, "io")
    ("OUT_n_A", OUT_n_A 0x55, "io")
    ("IN_B_C", IN_B_C, "io")
    ("OUT_C_B", OUT_C_B, "io")
    ("IN_C_C", IN_C_C, "io")
    ("OUT_C_C", OUT_C_C, "io")
    ("IN_D_C", IN_D_C, "io")
    ("OUT_C_D", OUT_C_D, "io")
    ("IN_E_C", IN_E_C, "io")
    ("OUT_C_E", OUT_C_E, "io")
    ("IN_H_C", IN_H_C, "io")
    ("OUT_C_H", OUT_C_H, "io")
    ("IN_L_C", IN_L_C, "io")
    ("OUT_C_L", OUT_C_L, "io")
    ("IN_A_C", IN_A_C, "io")
    ("OUT_C_A", OUT_C_A, "io")
    ("IN_PTR_C", IN_PTR_C, "io")
    ("OUT_C_0", OUT_C_0, "io")
    ]
