<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TimelineSelector.fs" />
    <Compile Include="FlameGraph.fs" />
    <Compile Include="ControlMap.fs" />
    <Compile Include="CheatEngineView.fs" />
    <Compile Include="GameOnlyView.fs" />
    <Compile Include="LauncherView.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JetpacFR.Core\JetpacFR.Core.fsproj" />
    <ProjectReference Include="..\Jetpac3.Core\Jetpac3.Core.fsproj" />
    <ProjectReference Include="..\Jetpac2.Core\Jetpac2.Core.fsproj" />
    <ProjectReference Include="..\Jetpac.Core\Jetpac.Core.fsproj" />
    <ProjectReference Include="..\..\games\minimal\JetpacFR.Game.Minimal.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
