module JetpacFRTests.GenGame

// The new-game project generator (plan_new_game_project):
//   --gen-game <gamesDir>/<id> --from <file> [--address N]
//       scaffold a game dir: original image + entry state + control.json
//       skeleton + the first CE version (v000_init).
//   --regen <gamesDir>/<id>
//       regenerate versions/ from control.json (block kinds respected),
//       writing vNNN_<tag>.fs and bumping activeVersion to it.
//   --materialize <gamesDir>/<id>
//       copy the active version over CeProgram.fs (the compiled file).
//   --diff-game <gamesDir>/<id> <a> <b>
//       assemble two versions, byte-diff each vs original.bin + raw stats.
//
// Every generated version must pass byte parity (assemble == image span)
// or it is refused - the gate from plan_ce_dsl stays absolute.

open System
open System.IO
open System.Text.Json
open JetpacFR.Core

module private Gen =
    /// Detect the non-zero extent of an already-normalized 64K image.
    let extentOf (mem: byte[]) (start: int) : int =
        let rec lastNonZero (i: int) : int =
            if i < start then start
            elif mem[i] <> 0uy then i + 1
            else lastNonZero (i - 1)

        max (start + 1) (min 0x10000 (lastNonZero (0x10000 - 1)))

    /// Normalize any input into original.bin: the game bytes laid out from
    /// their load address (.sna: 48K at $4000 with PC popped off the stack;
    /// anything else: bytes at `address`). Returns (path, start, endExcl,
    /// entryPc); the extent shrinks trailing zero padding.
    let normalizeImage (dir: string) (srcFile: string) (address: int) : string * int * int * int =
        let ext = Path.GetExtension(srcFile).ToLowerInvariant()
        let mem = Array.zeroCreate<byte> 0x10000

        let start, pc =
            if ext = ".sna" then
                let raw = File.ReadAllBytes srcFile

                if raw.Length < 27 + 48 * 1024 then
                    failwithf "SNA too short (%d bytes)" raw.Length
                // Header: 23..24 = SP; memory follows at offset 27. The 48K .sna
                // format stores no PC - it sits pushed on the stack.
                Array.blit raw 27 mem 0x4000 (48 * 1024)
                let sp = int raw[23] ||| (int raw[24] <<< 8)
                0x4000, (int mem[sp &&& 0xFFFF] ||| (int mem[(sp + 1) &&& 0xFFFF] <<< 8))
            else
                let raw = File.ReadAllBytes srcFile
                let len = min raw.Length (0x10000 - address)
                Array.blit raw 0 mem address len
                address, address

        let endExcl = extentOf mem start
        let binPath = Path.Combine(dir, "original.bin")
        File.WriteAllBytes(binPath, mem[start .. endExcl - 1])
        binPath, start, endExcl, pc


    let writeControl (dir: string) (imageFile: string) (start: int) (endExcl: int) (pc: int) : unit =
        let control =
            {| image = imageFile
               start = start
               endExcl = endExcl
               entryPc = pc
               activeVersion = 0
               blocks =
                [ {| start = start
                     endExcl = endExcl
                     name = "whole_span"
                     kind = "code" |} ] |}

        let json =
            JsonSerializer.Serialize(control, JsonSerializerOptions(WriteIndented = true))

        File.WriteAllText(Path.Combine(dir, "control.json"), json)

    /// Assemble a version body against its span and refuse non-parity output.
    let checkedVersionSource (gameId: string) (mem: byte[]) (c: GameControl) (body: string) : string =
        // Structural check: the emitted program text must reassemble to the
        // same bytes. Compile the body through Z80CE's structural twin
        // (toOps on the same span) - the source emitter and op emitter walk
        // identical boundaries, so parity of ops implies parity of the text.
        let ops = Z80CE.toOps mem c.Start (c.EndExcl - c.Start)
        let rebuilt = Jetpac2.Core.Z80.assemble ops
        let spanLen = c.EndExcl - c.Start
        let expected = mem[c.Start .. c.EndExcl - 1]

        if rebuilt.Length <> spanLen || rebuilt <> expected then
            let n = min rebuilt.Length expected.Length
            let mutable d = -1
            let mutable i = 0

            while d < 0 && i < n do
                if rebuilt[i] <> expected[i] then
                    d <- i

                i <- i + 1

            failwithf
                "%s: parity FAILED at %04X (%d vs %d bytes) - refusing to write the version"
                gameId
                (c.Start + max 0 d)
                rebuilt.Length
                expected.Length

        body

/// Emit Image.fs + Game.fs module texts for a scaffolded game.
module private Emit =

    let imageModule (moduleName: string) (tag: string) (body: string) : string =
        let sb = Text.StringBuilder()

        sb.AppendLine(sprintf "// GENERATED by --gen-game %s - regenerate via --regen, do not hand-edit." tag)
        |> ignore

        sb.AppendLine(sprintf "module %s" moduleName) |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open Jetpac2.Core") |> ignore
        sb.AppendLine("open Jetpac2.Core.Z80BuilderInstance") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// The active CE version as a runnable program.") |> ignore
        sb.AppendLine("let program : Z80Op list = z80 {") |> ignore
        sb.Append(body) |> ignore
        sb.AppendLine("}") |> ignore
        sb.ToString()

    /// The Fable-clean web module for a game: the live 64K machine capture
    /// (ROM + RAM) and the fresh image span as base64 literals (the
    /// Embedded.fs shape), the entry register state captured with it, and
    /// the whole span as ONE raw CE block. Execution of a raw block is the
    /// interpreter, so the web game plays exactly like the original.
    let webImageModule
        (moduleName: string)
        (gameId: string)
        (memory: byte[])
        (image: byte[])
        (entryState: string)
        (start: int)
        (endExcl: int)
        : string =
        let sb = Text.StringBuilder()

        let b64Chunks (b64: string) : string[] =
            b64 |> Seq.chunkBySize 92 |> Seq.map (fun ch -> System.String ch) |> Array.ofSeq

        let bytesLiteral (name: string) (doc: string) (bytes: byte[]) : unit =
            let chunks = bytes |> Convert.ToBase64String |> b64Chunks

            sb.AppendLine(sprintf "/// %s" doc) |> ignore

            sb.AppendLine(sprintf "let %s: byte[] = System.Convert.FromBase64String(" name)
            |> ignore

            chunks
            |> Array.iteri (fun i c ->
                let prefix = if i = 0 then "    \"" else "    + \""
                let suffix = if i = chunks.Length - 1 then "\")" else "\""
                sb.AppendLine(sprintf "%s%s%s" prefix c suffix) |> ignore)

            sb.AppendLine() |> ignore

        sb.AppendLine("// GENERATED by --null-ce --web-image - regenerate, do not hand-edit.") |> ignore
        sb.AppendLine(sprintf "module %s" moduleName) |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open Jetpac2.Core") |> ignore
        sb.AppendLine("open Jetpac2.Core.Z80BuilderInstance") |> ignore
        sb.AppendLine() |> ignore

        bytesLiteral
            "memory"
            (sprintf
                "The live 64K machine capture (ROM + RAM) the emulator starts from
/// (games/%s/memory.bin). Interrupts vector through the captured ROM, so
/// the CE run is faithful to the machine the snapshot came from."
                gameId)
            memory

        bytesLiteral
            "image"
            (sprintf
                "The fresh game image span [$%04X..$%04X) the CE program mirrors
/// byte-for-byte (original.bin)."
                start
                endExcl)
            image

        sb.AppendLine(sprintf "/// Entry register state captured with memory.bin (games/%s/state.txt)." gameId)
        |> ignore

        sb.AppendLine("let entryState: string =") |> ignore

        let stateLines = entryState.Replace("\r\n", "\n").TrimEnd('\n').Split '\n'

        if stateLines.Length = 1 && stateLines[0] = "" then
            sb.AppendLine("    \"\"") |> ignore
        else
            stateLines
            |> Array.iteri (fun i line ->
                let escaped = line.Replace("\\", "\\\\").Replace("\"", "\\\"")
                let prefix = if i = 0 then "    \"" else "    + \""

                sb.AppendLine(sprintf "%s%s\\n\"" prefix escaped) |> ignore)

        sb.AppendLine() |> ignore

        sb.AppendLine("/// The null CE: the whole span as one raw block. Raw bytes execute") |> ignore
        sb.AppendLine("/// through the interpreter, exactly like the original game; the CE") |> ignore
        sb.AppendLine("/// index only maps PC into the span.") |> ignore
        sb.AppendLine("let program: Z80Op list =") |> ignore
        sb.AppendLine("    z80 {") |> ignore
        sb.AppendLine("        yield! image") |> ignore
        sb.AppendLine("    }") |> ignore

        sb.ToString()

    let runnerModule (moduleName: string) (imageModuleName: string) (entryPc: int) : string =
        let sb = Text.StringBuilder()

        sb.AppendLine(sprintf "// GENERATED by --gen-game - regenerate via --regen, do not hand-edit.")
        |> ignore

        sb.AppendLine(sprintf "module %s" moduleName) |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("open Jetpac2.Core") |> ignore
        sb.AppendLine("open JetpacFR.Core") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("/// The registry bundle shells look up by GameId.") |> ignore
        sb.AppendLine("let register () =") |> ignore
        sb.AppendLine("  GameRegistry.register") |> ignore
        sb.AppendLine("    { GameId = \"%GAMEID%\"") |> ignore
        sb.AppendLine("      Name = \"%GAMENAME%\"") |> ignore
        sb.AppendLine("      Memory = %MEMORYEXPR%") |> ignore
        sb.AppendLine("      Program = %IMAGEMODULE%.program") |> ignore
        sb.AppendLine("      EntryState = \"\" }") |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine(sprintf "/// Entry PC: 0x%04X" entryPc) |> ignore
        sb.ToString()

/// One-shot generation pipeline shared by gen/regen/materialize.
module private Pipeline =

    let loadOrInitControl (dir: string) : GameControl = GameProject.loadControl dir

    /// Next free vNNN index (vNNN_<tag>.fs names only; other v*.fs names
    /// don't participate).
    let nextVersionIndex (dir: string) : int =
        let vd = Path.Combine(dir, "versions")

        if Directory.Exists vd then
            (Directory.GetFiles(vd, "v*.fs")
             |> Array.choose (fun f ->
                 let name = Path.GetFileName f

                 if name.Length >= 4 && (name.Substring(1, 3) |> Seq.forall System.Char.IsDigit) then
                     Some(int (name.Substring(1, 3)))
                 else
                     None)
             |> fun a -> if a.Length = 0 then -1 else Array.max a)
            + 1
        else
            0

    /// Rewrite control.json's activeVersion (preserve other fields).
    let bumpActiveVersion (dir: string) (idx: int) : unit =
        let ctrlPath = Path.Combine(dir, "control.json")
        use doc = JsonDocument.Parse(File.ReadAllText ctrlPath)
        let out = new IO.MemoryStream()

        do
            use w = new Utf8JsonWriter(out, JsonWriterOptions(Indented = true))
            w.WriteStartObject()
            let mutable wroteActive = false

            for p in doc.RootElement.EnumerateObject() do
                if p.Name = "activeVersion" then
                    w.WriteNumber("activeVersion", idx)
                    wroteActive <- true
                else
                    p.WriteTo w

            if not wroteActive then
                w.WriteNumber("activeVersion", idx)

            w.WriteEndObject()

        File.WriteAllText(ctrlPath, Text.Encoding.UTF8.GetString(out.ToArray()))

    /// Regenerate the NEXT version from control.json + original.bin and make
    /// it active. Tag describes the change (default: block-map revision).
    let regen (dir: string) (tag: string option) : string =
        let gameId = DirectoryInfo(dir).Name.ToLowerInvariant()
        let c = GameProject.loadControl dir
        let mem = GameProject.loadImage dir c
        // Body assembly per block kind: code walks instructions, data/gap stay
        // single labeled raw blocks. Control-file comments are woven in as //
        // lines: names become section headers, line comments attach to their
        // address, range comments open at the range start.
        let sb = Text.StringBuilder()
        // Parse errors must propagate: silently degrading to a comment-less
        // version hides corruption in control.json.
        let cf =
            if File.Exists(Path.Combine(dir, "control.json")) then
                Some(ControlFile.load dir)
            else
                None

        let commentsAt (addr: int) : ControlComment list =
            match cf with
            | Some c -> c.Comments |> List.filter (fun m -> m.Kind = Line && m.Addr = addr)
            | None -> []

        let nameHeaders: ControlComment list =
            match cf with
            | Some c -> ControlFile.namesSorted c
            | None -> []

        let rangeComments (addr: int) : ControlComment list =
            match cf with
            | Some c -> c.Comments |> List.filter (fun m -> m.Kind = Range && m.Addr = addr)
            | None -> []

        let emitComments (addr: int) : unit =
            for h in nameHeaders do
                if h.Addr = addr then
                    sb.AppendLine(sprintf "  // ========== %s ($%04X) ==========" h.Text addr)
                    |> ignore

            for r in rangeComments addr do
                sb.AppendLine(sprintf "  // [%04X..] %s" r.Addr r.Text) |> ignore

            for m in commentsAt addr do
                sb.AppendLine(sprintf "  // $%04X: %s" addr m.Text) |> ignore

        let mutable cursor = c.Start
        // Function symbols (control.json) become named label cells in the CE;
        // toBody restricts them to each block's span.
        let symbols =
            match cf with
            | Some cf -> ControlFile.symbolsSorted cf
            | None -> []

        for b in c.Blocks do
            emitComments b.Start

            match b.Kind with
            | Code -> sb.Append(Z80CE.toBody mem b.Start (b.EndExcl - b.Start) true symbols) |> ignore
            | Data
            | Gap ->
                let bytes = mem[b.Start .. b.EndExcl - 1]
                let hex = bytes |> Array.map (fun x -> sprintf "0x%02Xuy" x) |> String.concat "; "

                sb.AppendLine(
                    sprintf
                        "  // %s (%s)"
                        b.Name
                        (match b.Kind with
                         | Data -> "data"
                         | _ -> "gap")
                )
                |> ignore

                sb.AppendLine(sprintf "  yield! [| %s |]" hex) |> ignore

            cursor <- b.EndExcl

        if cursor < c.EndExcl then
            failwithf
                "blocks cover [%06X,%06X) but span ends at %06X - add a block or shrink endExcl"
                c.Start
                cursor
                c.EndExcl

        let tag' =
            tag |> Option.defaultWith (fun () -> sprintf "blocks%d" (List.length c.Blocks))
        // Parity gate over what will actually be emitted: the per-block op
        // stream concatenated exactly as the body above. A Code block boundary
        // that splits an instruction makes the emitted stream differ from the
        // image (the straddled bytes appear twice), which a whole-span decode
        // cannot see; Data/Gap blocks re-emit their literal bytes.
        let emittedOps =
            c.Blocks
            |> List.collect (fun b ->
                match b.Kind with
                | Code -> Z80CE.toOps mem b.Start (b.EndExcl - b.Start)
                | Data
                | Gap -> [ Z80CE.rawOp (mem[b.Start .. b.EndExcl - 1]) ])

        let rebuilt = Jetpac2.Core.Z80.assemble emittedOps
        let expected = mem[c.Start .. c.EndExcl - 1]

        if rebuilt <> expected then
            let n = min rebuilt.Length expected.Length
            let mutable d = -1
            let mutable i = 0

            while d < 0 && i < n do
                if rebuilt[i] <> expected[i] then
                    d <- i

                i <- i + 1

            failwithf
                "%s: parity FAILED at %04X (%d vs %d bytes) - refusing to write the version"
                gameId
                (c.Start + max 0 d)
                rebuilt.Length
                expected.Length

        let idx = nextVersionIndex dir
        let file = Path.Combine(dir, "versions", sprintf "v%03d_%s.fs" idx tag')
        Directory.CreateDirectory(Path.GetDirectoryName file) |> ignore

        let header =
            sprintf
                "// GENERATED by --regen from control.json (activeVersion bumped by the caller).\r\n// blocks: %d\r\n"
                (List.length c.Blocks)

        File.WriteAllText(file, header + sb.ToString())
        // Bump activeVersion in control.json (preserve other fields by rewrite).
        bumpActiveVersion dir idx
        printfn "regen: %s" file
        file

    let materialize (dir: string) : unit =
        let copied = GameProject.materialize dir
        printfn "materialize: CeProgram.fs <- %s" copied

    /// The null CE: every block re-emitted as raw bytes (no labels, no vocab
    /// ops) - the default "raw bytes in the CE file" version. Raw blocks
    /// execute through the interpreter, so the run is byte-exact by
    /// construction; the parity gate asserts it anyway. The new version
    /// becomes active and CeProgram.fs is materialized from it.
    let nullCe (dir: string) (withWebImage: bool) : unit =
        let gameId = DirectoryInfo(dir).Name.ToLowerInvariant()
        let c = GameProject.loadControl dir
        let mem = GameProject.loadImage dir c
        let sb = Text.StringBuilder()
        let mutable cursor = c.Start
        let mutable emitted: Jetpac2.Core.Z80Op list = []

        for b in c.Blocks do
            if b.Start <> cursor then
                failwithf
                    "blocks must tile [%04X,%04X): %s starts at %04X"
                    c.Start
                    c.EndExcl
                    b.Name
                    b.Start

            let bytes = mem[b.Start .. b.EndExcl - 1]
            let hex = bytes |> Array.map (fun x -> sprintf "0x%02Xuy" x) |> String.concat "; "

            sb.AppendLine(sprintf "  // %s" b.Name) |> ignore
            sb.AppendLine(sprintf "  yield! [| %s |]" hex) |> ignore
            emitted <- Z80CE.rawOp bytes :: emitted
            cursor <- b.EndExcl

        if cursor < c.EndExcl then
            failwithf
                "blocks cover [%06X,%06X) but span ends at %06X - add a block or shrink endExcl"
                c.Start
                cursor
                c.EndExcl

        let emitted = List.rev emitted
        let rebuilt = Jetpac2.Core.Z80.assemble emitted
        let expected = mem[c.Start .. c.EndExcl - 1]

        if rebuilt <> expected then
            failwithf
                "%s: null CE parity FAILED (%d vs %d bytes) - refusing to write the version"
                gameId
                rebuilt.Length
                expected.Length

        let idx = nextVersionIndex dir
        let file = Path.Combine(dir, "versions", sprintf "v%03d_nullce.fs" idx)
        Directory.CreateDirectory(Path.GetDirectoryName file) |> ignore

        let header =
            sprintf
                "// GENERATED by --null-ce: the raw-bytes default version (no labels, no vocab ops).\r\n// blocks: %d\r\n"
                (List.length c.Blocks)

        File.WriteAllText(file, header + sb.ToString())
        bumpActiveVersion dir idx
        let materialized = GameProject.materialize dir
        printfn "null-ce: %s (parity OK, %d bytes raw)" file (c.EndExcl - c.Start)
        printfn "materialize: CeProgram.fs <- %s" materialized

        if withWebImage then
            let memPath = Path.Combine(dir, "memory.bin")
            let statePath = Path.Combine(dir, "state.txt")

            if not (File.Exists memPath) || not (File.Exists statePath) then
                failwithf "--web-image needs %s and %s (the live 64K capture + its register state)" memPath statePath

            let cap (s: string) = s[0].ToString().ToUpperInvariant() + s.Substring(1)
            let moduleName = sprintf "%sGame.WebImage" (cap gameId)

            let text =
                Emit.webImageModule
                    moduleName
                    gameId
                    (File.ReadAllBytes memPath)
                    expected
                    (File.ReadAllText statePath)
                    c.Start
                    c.EndExcl

            let webPath = Path.Combine(dir, "WebImage.fs")
            File.WriteAllText(webPath, text)
            printfn "web-image: %s (%s)" webPath moduleName

/// CLI surface.
let run (argv: string list) : int =
    match argv with
    | "--gen-game" :: dir :: rest ->
        let rec parse (acc: Map<string, string>) (xs: string list) =
            match xs with
            | flag :: v :: t when flag.StartsWith "--" -> parse (acc.Add(flag.Substring(2), v)) t
            | [] -> acc
            | bad ->
                eprintfn "bad args near %A" bad
                exit 2

        let opts = parse Map.empty rest

        let src =
            match opts.TryFind "from" with
            | Some f -> f
            | None ->
                eprintfn "--gen-game needs --from <file>"
                exit 2

        let address =
            opts |> Map.tryFind "address" |> Option.map int |> Option.defaultValue 0x8000

        let name =
            opts
            |> Map.tryFind "name"
            |> Option.defaultWith (fun () -> DirectoryInfo(dir).Name)

        if not (Directory.Exists dir) then
            Directory.CreateDirectory dir |> ignore

        if not (Directory.Exists dir) then
            eprintfn "cannot create %s" dir
            exit 2

        let bin, start, endExcl, pc = Gen.normalizeImage dir src address
        Gen.writeControl dir (Path.GetFileName bin) start endExcl pc
        // v000_init: whole span as code.
        let c = GameProject.loadControl dir
        let mem = GameProject.loadImage dir c

        let body =
            Gen.checkedVersionSource
                (DirectoryInfo(dir).Name.ToLowerInvariant())
                mem
                c
                (Z80CE.toBody mem c.Start (c.EndExcl - c.Start) true [])

        let vd = Path.Combine(dir, "versions")
        Directory.CreateDirectory vd |> ignore

        File.WriteAllText(
            Path.Combine(vd, "v000_init.fs"),
            "// GENERATED by --gen-game (initial whole-span disassembly)\n" + body
        )

        printfn "gen-game: %s" dir
        printfn "  original.bin  %d bytes @ $%04X (span $%04X-$%04X)" (FileInfo(bin)).Length start start endExcl
        printfn "  control.json  entryPc=$%04X, blocks=1 (code)" pc
        printfn "  v000_init.fs  written (active)"

        printfn
            "next: edit games/%s/control.json (mark data/gap blocks), then run:"
            (DirectoryInfo(dir).Name.ToLowerInvariant())

        printfn
            "  dotnet run --project tests/JetpacFR.Core.Tests -- --regen games/%s --tag <what-changed>"
            (DirectoryInfo(dir).Name.ToLowerInvariant())

        0
    | "--regen" :: dir :: rest ->
        let tag =
            rest
            |> function
                | "--tag" :: t :: _ -> Some t
                | _ -> None

        Pipeline.regen dir tag |> ignore
        Pipeline.materialize dir
        0
    | "--null-ce" :: dir :: rest ->
        let withWebImage = rest |> List.contains "--web-image"
        Pipeline.nullCe dir withWebImage
        0
    | "--capture-tape" :: tzxPath :: outDir :: rest ->
        let rec parse (acc: Map<string, string>) (xs: string list) =
            match xs with
            | flag :: v :: t when flag.StartsWith "--" -> parse (acc.Add(flag.Substring(2), v)) t
            | [] -> acc
            | bad ->
                eprintfn "bad args near %A" bad
                exit 2

        let opts = parse Map.empty rest
        let romPath = opts |> Map.tryFind "rom" |> Option.defaultValue "assets/48.rom"
        let settle = opts |> Map.tryFind "settle" |> Option.map int |> Option.defaultValue 1800

        // Boot the real tape (ROM + TZX through the oracle), run past the
        // load into gameplay, then capture the live machine. This is the
        // honest warm-start for a CE run: RAM, ROM, and registers all come
        // from one moment of a real session.
        let spec, entryCycles = Jetpac3.Core.Boot.bootToEntry romPath tzxPath None

        for _ in 1 .. settle do
            spec.RunFrame()

        let mem, state = spec.SaveState()
        printfn "capture: boot entry at cycles %d, settled %d frames, state pc=%s" entryCycles settle (state.Split('\n') |> Array.find (fun l -> l.StartsWith "pc="))

        let backup (name: string) =
            let p = Path.Combine(outDir, name)

            if File.Exists p then
                let bak = Path.ChangeExtension(p, ".bak")

                if not (File.Exists bak) then
                    File.Copy(p, bak)

        backup "memory.bin"
        backup "state.txt"
        File.WriteAllBytes(Path.Combine(outDir, "memory.bin"), mem)
        File.WriteAllText(Path.Combine(outDir, "state.txt"), state)
        printfn "capture: %s" (Path.Combine(outDir, "memory.bin"))
        printfn "capture: %s" (Path.Combine(outDir, "state.txt"))
        0
    | "--materialize" :: dir :: _ ->
        Pipeline.materialize dir
        0
    | "--diff-game" :: dir :: a :: b :: _ ->
        let c = GameProject.loadControl dir
        let mem = GameProject.loadImage dir c
        let span = c.EndExcl - c.Start
        let expected = mem[c.Start .. c.EndExcl - 1]
        let vd = Path.Combine(dir, "versions")

        let resolveVersion (arg: string) : string =
            let direct = Path.Combine(vd, if arg.EndsWith ".fs" then arg else arg + ".fs")

            if File.Exists direct then
                direct
            else
                // Prefix match: "v2" or "v002" resolves to versions/v002_*.fs.
                let matches =
                    if Directory.Exists vd then
                        Directory.GetFiles(vd, "v*.fs")
                        |> Array.filter (fun f ->
                            (Path.GetFileName f).StartsWith(arg, StringComparison.OrdinalIgnoreCase))
                    else
                        [||]

                match matches with
                | [| single |] -> single
                | _ -> failwithf "version '%s' not found in %s (use a vNNN prefix or file name)" arg vd

        let stats (label: string) (path: string) : unit =
            let body = File.ReadAllText path
            // The version file is a generated z80 body (plus header). Two checks:
            // does it still match what regeneration produces from control.json
            // (catches hand edits and stale versions), and does the structural
            // span decode assemble back byte-for-byte. Symbols are included so a
            // named control file does not read as a hand edit.
            let symbols =
                if File.Exists(Path.Combine(dir, "control.json")) then
                    ControlFile.symbolsSorted (ControlFile.load dir)
                else
                    []

            let regenBody = Z80CE.toBody mem c.Start span true symbols
            let matchesRegen = body.Contains regenBody
            let ops = Z80CE.toOps mem c.Start span
            let asm = Jetpac2.Core.Z80.assemble ops

            let mismatches =
                [ for i in 0 .. min (asm.Length - 1) (expected.Length - 1) do
                      if asm[i] <> expected[i] then
                          i ]

            let rawBytes =
                ops
                |> List.filter (fun o -> o.Mnemonic = "raw")
                |> List.sumBy (fun o -> o.Bytes.Length)

            let pctRaw = float rawBytes * 100.0 / float span

            let status =
                if not (mismatches.IsEmpty && asm.Length = span) then
                    sprintf
                        "SPAN MISMATCH (%d bytes, first at +%d)"
                        mismatches.Length
                        (if mismatches.IsEmpty then -1 else mismatches.Head)
                elif not matchesRegen then
                    "DIFFERS FROM REGEN (hand-edited or stale?)"
                else
                    "PARITY OK"

            printfn "%-12s %s: %s, %d ops, raw %.1f%%" label (Path.GetFileName path) status ops.Length pctRaw

        stats a (resolveVersion a)
        stats b (resolveVersion b)
        0
    | _ ->
        eprintfn "usage:"
        eprintfn "  --gen-game <dir> --from <bin|sna> [--address N] [--name NAME]"
        eprintfn "  --regen <dir> [--tag TAG]"
        eprintfn "  --null-ce <dir> [--web-image]"
        eprintfn "  --capture-tape <tzx> <outDir> [--rom PATH] [--settle FRAMES]"
        eprintfn "  --materialize <dir>"
        eprintfn "  --diff-game <dir> <verA> <verB>"
        2
