# -*- coding: utf-8 -*-
"""Merge the mechanical funcref skeleton (uridium_funcref_raw.txt, generated by
bench codemap mode) with the manual Uridium analysis -> uridium_function_reference.txt

Structure:
  PART 1 - documented functions & anchors (manual analysis, sorted by address)
  PART 2 - additional recursive-map functions (mechanical info only, ROM noted)
"""
import re

D = {}
def F(addr, name, inp, outp, desc):
    D[addr] = (name, "FUNC", inp, outp, desc)
def DATA(addr, name, desc):
    D[addr] = (name, "DATA", "-", "-", desc)

# ---- loader chain (executed at game start) ----
F(0x5D93, "uridium_multiload_stub", "none (BASIC hands over control)", "PC=$F500, continuation code copied", "Copies $014F loader bytes from the BASIC/channel area to $F500 and RETs into them.")
F(0xF500, "loader_init", "memory = first-load 48K image", "screen cleared, attributes painted, loader registers primed", "DI; clear screen bitmap $4000-$5AB4 (BC=$1CB5); paint title attribute bands; prepare the tape-read state machine.")
F(0xF50F, "loader_paint_attributes", "A=$FE attribute byte, HL=$55C1", "attribute rows at $55C1+ written", "Paints the title colour bands into the attribute area.")
F(0xF520, "loader_set_alt_fill_regs", "none", "BC'=$FFFF, DE'=$4242", "Preloads the shadow-register fill byte (0x42) used later by glyph drawing.")
F(0xF527, "loader_setup_load_regs", "none", "SP=$FCFF, DE=$C000, IX=$4000", "Sets the loader stack, the remaining load length ($C000) and the destination address.")
F(0xF540, "tape_sample_ear_into_c", "none", "C = EAR bit masked $20, Z flag set", "Reads the EAR input once and primes the edge-polarity state for the sampler.")
F(0xF547, "loader_reentry_ret_nz", "flags from the sampler", "returns when an EAR edge is seen", "Conditional re-entry of the tape sampler loop (falls through on the primed state).")
F(0xF5FB, "tape_wait_ear_edge", "B = timeout counter, C = last edge state", "CY set when edge found before timeout", "Samples EAR (IN $7FFE / RRA) until a pulse edge or timeout - the tape bit reader.")
F(0xF54B, "tape_edge_sync_loop", "none", "CY state", "JR NC sync loop of the tape bit reader (waits for the next pulse edge).")
F(0xF5E8, "loader_delay_and_store", "DE = loader position", "($5AC1) = DE", "Short delay then stashes the loader read position.")

# ---- statically verified functions ----
F(0xA8A9, "interrupt_init_im2", "IY = vector base", "IM 2 active, ($FDFD) = vector byte, $FF01.. slots filled", "Switches to interrupt mode 2, installs the vector table, then CALLs $9C36 to stage the title text.")
F(0x88B4, "init_game_vars", "A = level/game variant", "state vars $DB1F/$DA5F/$D87B/$DB1A/$DC39 = 0; $D939 = $FF; IX = selected table", "Resets the game state and selects the level table pair ($DB78/$DBD8) by ($D99E).")
F(0x8FA7, "object_list_unlink_iy", "IY -> object record, HL -> list cursor", "list links rewritten, head $9391 updated", "Unlinks/inserts an object in the linked list using the IY table at $D756.")
F(0x9C36, "copy_counted_text", "HL -> counted text, DE -> destination, B = count", "text copied to destination", "Counted string copy used to stage title/credit text for display.")
F(0x8F34, "store_hl_a_earlyout", "A = value, HL -> address", "(HL) = A unless A=0-flag or $7C", "Guarded byte write; the most frequently used helper in the first load (9 call sites).")

# ---- wave / object system ----
F(0x9435, "spawn_wave_objects", "IY -> wave definition table, IX -> object pool cursor", "up to 6 objects created in the $FF70 pool; wave state $D93A/$DC39 set", "Walks wave entries, fills 16-byte objects (position, type, anim, flags), scans sprite tables at $67B0 with CPIR for $FF frame terminators.")
F(0x9379, "object_move_y_clamp_6f", "IX -> object, HL/DE -> player position reference", "(IX+6) Y updated, clamped to $6F", "If the object is within $1F4 of the player, adds its signed Y velocity (+0F) with clamping.")
F(0x92BF, "apply_wave_scroll_to_object", "IX -> object, ($FFF0) = wave scroll vector", "(IX+$0C/$0D) -= scroll", "Applies the wave scroll vector to an object position.")
F(0x91BB, "dispatch_object_updates", "IX = $FF70 object pool, IY = $DCFA counters", "each active object's behaviour routine runs", "Iterates 7 objects x $10 bytes; BIT 1,(IX+2) gates dispatch; jump table at $81B3 indexed by type.")
F(0x9163, "score_add_bonus_to_counters", "A = bonus class, HL -> 3-byte counter", "counter increased (+8, +B, +B, +B with carries)", "Classifies the bonus into ranges (4/7) and adds it to the 24-bit score counters at offsets $162/$163.")
F(0x96D8, "enemy_move_chase_player", "IX -> enemy object, ($FF56) = player X", "object position/velocity updated; expiry CALLs $884E", "Enemy AI: timers (IX+A)/(IX+8) expire, steers X toward the player, moves Y clamped to $6F, tail JP $81E0.")
F(0x994B, "check_objects_near_player", "IY -> object list, B = count, HL/DE = player position", "proximity result; type 3 objects CALL $8A7D", "Flag tests then Y-distance < $18 proximity check between objects and the player.")
F(0x98EF, "spawn_object_from_object", "IX = parent object, IY = target slot", "new object with copied type/position and launch offset ($FFF8/$10)", "Spawns a projectile/child object from a parent and increments the wave counter ($D93A).")
F(0x9A24, "init_formation_from_data", "HL -> 3 bytes per object, IX -> pool cursor, C = X base", "6 objects initialised (anim +0A, delay +9+$0C, X +6)", "Builds an enemy formation from level data bytes, staging attributes at $5B8F.")
F(0x9A7C, "check_hitbox_28x29", "IY -> object A, IX -> object B", "on overlap: JP $8992 (hit handler)", "AABB collision test: X within $52..$6E of ($D75C), Y within $1D of (IY+6)+$0E.")
F(0x8FE3, "allocator_swap_node_fd52", "BC = node, A = value", "chain at $FD52 searched, node value swapped with ($FD50)", "The in-game list allocator's free/realloc: LDI x3 copy plus linked search and swap.")
F(0x8BB4, "title_init_panels", "none", "panel objects IX=$8C4A/$8C58 sized 6/5 at attrs $582B/$584B", "Initialises the two title screen status panels and pokes $8F34 with 0 and 1.")
F(0x8B2C, "clamp_store_max_dc3b", "A = value", "($DC3B) = max(old value, A)", "Monotonic maximum store - keeps the largest observed value.")
F(0x8C24, "compute_wave_timing_params", "D, E, B = wave difficulty numbers", "$DC9D/$DC9E/$DC98 = D/4+E; $DC99 = $30+D+2E; $DC9A/$DC9B = max(8, B*4+D/2)", "Derives the wave cadence and speed parameters from the level numbers.")
F(0x8EAC, "move_object_x_clamped", "A = input delta, IX -> object", "(IX+4/5) X position moved", "Applies the signed direction ($D81F, magnitude < $0B) to the object X with bounds $FFA0..$0B87.")
F(0x8F67, "build_object_list_d756", "B = groups, C = table index, HL -> output cursor", "object list assembled; head at $9391 relinked", "Builds an object list from table $D756 (B groups x 8 entries via CALL $9385).")
F(0x9EAC, "draw_sprite_4x2", "IX -> object, ($D8D9/$D8DB) position, ($D8DD) -> source", "4x2 attribute cells drawn to the bitmap", "Char-row screen address calculation (RLCA x3) and masked sprite blit.")
F(0x8A7D, "object_update_sequencer", "IX -> object, HL/DE = context", "sub-behaviours run; counters $DB1E/$DC9B updated", "Per-frame sequencer: CALLs $8124, $7A4F, $8856, $9379, $795E, $8AB0 in order, then wave-state tests.")
F(0x8856, "sprite_plot_bytes", "HL -> sprite bytes, BC -> screen address", "pixel bytes written to the bitmap", "Sprite blit inner loop: LD H,(HL) / LD C,H / LD D,(HL) then LD (BC),A per pixel byte.")
F(0x9385, "object_move_y_guarded", "IX -> object, HL/DE -> player reference", "(IX+6) Y moved if within $1F4, clamped $6F", "Guarded shared Y-movement helper (the $9379 family tail).")
F(0x8F16, "check_table_byte_d75a", "DE = offset, (HL) = base", "Z flag when the probed byte >> 3 equals $77", "Probes a byte in the table at ($D75A)+DE+$0A.")
F(0x884E, "sprite_plot_on_expire", "IX -> object", "sprite bytes re-plotted", "Blit entry used when an enemy object timer expires (CALL from the enemy move path).")
F(0x89E9, "copy_block_ldir", "HL -> source, DE -> destination, BC = length", "block copied", "LDIR wrapper.")
F(0x8AD0, "wave_pattern_setup", "IX = ($DB1B) panel objects, ($D99E) = level", "$8D79 patched from ($D99E)+$B0; object list rebuilt; $4B bytes of $7BE7 drawn", "Per-wave pattern bring-up: rebuilds the list, pokes the title helpers, runs the dispatcher tail.")
F(0x7BE7, "timed_wait_draw_loop", "B = iteration count ($32 or $4B)", "timed delay, glyph bytes $41/$00/$16 processed", "Parameterised wait-and-draw loop used for title panel animation and wave waits.")
F(0x8B4F, "compute_attr_index_iy2", "IY+2 = object attribute byte", "A = colour index, range-checked against $90", "Attribute colour index calculation from the object flags.")
F(0x8CF7, "clear_wave_objects", "HL -> start, DE = stride, B = count", "object array zeroed; ($DC39) = 0", "Zeroes the object array (fill loop) and resets the wave state.")
F(0x8D01, "move_object_x_check_limits", "IX -> object", "movement allowed or blocked (CALL $7DDD)", "Direction gate ($D81F >= 4) and position bound checks against $FF54 and $0B76.")
F(0x97D0, "init_object_attrs_5b98", "IX -> object pool", "first inactive object gets (IX+7)=3 and attrs at $5B98", "Scans the 7 pool objects and initialises the attribute cell for the next one.")
F(0x9ADD, "select_variant_and_rebuild", "C = menu/state flags", "($D99D) = 1 or 2", "Selects the game variant from the menu flags and rebuilds the object list ($8FA7) plus $7BA5.")
F(0x9B49, "title_screen_init_seq", "A = count, HL/DE = copy parameters", "title panels/objects initialised via $8BC4 x2, $8AD0, $938E", "The first-load title screen bring-up sequence.")
F(0xA00D, "scan_title_panels_8", "IX = $D8DF panel links, HL = $9044 names", "8 panels scanned at $58D7 with $32 stride", "Title panel table scan using $8F16/$8F26 checks.")
F(0x954C, "store_object_ptr_d93c", "IX -> current object", "($D93C) = IX+3/4", "Remembers the current object pointer for the dispatcher.")

# ---- pass 3 ----
F(0x9BCB, "title_selection_blip", "($D8D8) = state", "border pulse + timed delay", "EI/HALT/DI interrupt wait then border OUT ($FE) - audible/visible selection feedback.")
F(0x9FE3, "panels_reinit_next_screen", "none", "panel objects $8C4A/$8C58 re-aimed at attrs $580B/$582B; $8F34 pokes 0/1/$0A", "Moves the title panel objects to their next-screen positions and re-arms them.")
F(0xA000, "title_panel_scan_init", "none", "($D8DD)=0; IX=$D8DF self-linked", "Initialises the title panel scan state (the scan itself at $A00D is inside this function).")
F(0xA0B7, "title_init_variant_b", "($D7BF) = variant flag", "panels/wave setup via $8BC4, $8AD0, $938E", "Alternate title bring-up path selected by the variant flag.")
F(0xA175, "apply_level_speed_table", "($D99E) = level number", "speed cells at $91CF+ filled from $D9F8/$D9FC", "Selects the per-level speed table and ADCs the values into the panel speed cells.")
F(0xA1FC, "scroll_title_panels", "($D99E) = level number", "8 title panels scrolled via CALL $92AA with the $9078 table", "Scrolls the title panels by the level speed (pass-2 anchor $A200 is inside this function).")
F(0xA2E1, "title_anim_step_with_sound", "HL -> panel", "panel scanned ($8F16), list rebuilt ($8F67), timed sound loop (XOR $F8)", "One step of the title animation including the sound toggle preparation.")
F(0xA379, "object_behaviour_jumptable", "A = object type index", "JP to the behaviour routine", "Trampoline table: $9567/$957D/$95AE/$95B7/$98EF/$9CFD/$9A24/$9AB5/$954C/$9D3C.")
F(0xA3EA, "switch_to_object_stack", "current SP = frame to save, IY = new stack", "SP = IY, registers restored from the new frame", "Switches the CPU stack to an object's own frame (dispatcher helper).")
F(0xA4AE, "find_free_3byte_entry", "DE -> table start, ($6A17) = hint", "HL -> first free entry", "Scans 3-byte entries until the $80 end-flag is seen.")
F(0xA4F7, "calc_sprite_addr_from_y", "HL -> Y position pair", "D = bitmap row third from the $62xx row table", "Converts a Y coordinate into a bitmap address via the screen-row lookup.")
F(0xA5AB, "copy_block_ldir_ret", "HL/DE/BC", "block copied", "LDIR; RET block-copy variant.")
F(0xA5AE, "set_variant1_after_walk", "none", "($D99D) = 1", "Runs the $9899 table walk then forces game variant 1.")
F(0xA5B7, "proximity_check_wrapper", "object registers", "proximity check results", "Sequential wrapper: CALL $994B then CALL $997E.")
F(0xA5BE, "save_sp_setup_wave", "current SP", "($96D5) = SP; DE = ($D75E) + $F8", "Parks the dispatcher stack pointer and prepares the wave pointer.")
F(0xA702, "spawn_next_wave_object", "($DAB9) = current index", "E = index+1, D = $7E", "Advances the wave object index and jumps into the spawn path ($971D).")
F(0xA796, "wave_state_advance", "($DC3B) marker, ($DC3A) counter", "table $9853 selected or state advanced", "Wave-completion state machine driven by the clamp-stored marker.")
F(0xA827, "engine_tone_out", "C = iterations, ($9811) = port shadow", "EAR bit toggled - square wave output", "Engine/sound-effect tone: XOR $F8 then OUT ($FE),A inside a timed loop.")
F(0xA92A, "push_object_defaults", "HL -> default values, IX -> object", "defaults pushed onto the object stack", "Preloads object initial values with a PUSH pattern ($0C rounds).")
F(0xA97E, "allocator_init_chain_fd52", "none", "$FD50/$FD52 = $FD54; 11 free nodes, stride $0E", "Initialises the in-game allocator free chain (used by $8FE3).")
F(0xA9A1, "init_formation_pool_ff10", "HL anchors -> ($D7B8/$D7BA/$D7BC)", "16 formations initialised via CALL $9A24 into the $FF10 pool", "Builds the second formation pool from the $D750 definitions.")
F(0xAABB, "read_input_port_fe", "none", "A = active-low key bits of the selected half-row", "Reads a keyboard/EAR half-row and complements it (menu input cluster $AABB-$AAF2).")
F(0xAD15, "handle_menu_keys", "C = menu/state flags", "key handler routed ($9C15, $9B90 with DE=$B860)", "Dispatches menu key processing including the space-key waiter.")
F(0xAD87, "xor_blit_masked", "HL -> source, DE -> destination, B/C = masks", "masked XOR bytes written to the destination", "Masked sprite XOR-blit step.")
F(0xB130, "title_scroll_dispatch", "($DAB8) = speed selector", "($A1F3) patched, then the $A1FC scroll path", "Chooses the title scroll variant from the speed selector.")
F(0xB209, "update_object_attrs_loop", "IY -> objects, DE = stride, HL -> reference", "(IY+4) refreshed from ($D99A) when the type differs", "Per-object attribute refresh loop.")
F(0xB860, "wait_for_space_keypress", "none", "returns after Space press and release (row $FB)", "Waits for a Space keypress with a release debounce loop.")
F(0xBCE0, "reinit_sysvars_and_stack", "none", "sysvars $5C0B-$5CB5 cleared; SP=$FCFF; allocator $FD50 primed", "Post-load handover: resets the BASIC system area and prepares the game stack/allocator.")
F(0xAC4A, "reposition_object_offscreen", "IX -> object, ($D75C) = wave scroll", "object RES 0 (+2) and re-aimed at the scroll position", "Recycles off-screen objects: clears the active bit and re-aims at the wave scroll.")
F(0x91FC, "advance_sprite_frame", "IX -> object, HL -> sprite-definition chain", "frame pointer (IX+9/A) and delay (IX+B) advanced", "Walks the $FF-terminated sprite-def chain and steps the animation frame.")

# ---- data anchors ----
DATA(0x5CFE, "multiload_name_ucode", "Multiload filename 'Ucode'.")
DATA(0x5D13, "multiload_name_screen", "Multiload filename 'screen'.")
DATA(0x5D60, "multiload_name_part2", "Multiload filename 'part2'.")
DATA(0x5D86, "multiload_name_lastpart", "Multiload filename 'lastpart'.")
DATA(0x9C74, "credits_present_text", "Title credits: ' Present ...'")
DATA(0x9C81, "credits_graftgold", "Title credits: 'Graftgold Ltd 198..'.")
DATA(0x9C99, "credits_hewson", "Title credits: 'Hewson 198..'.")
DATA(0x9CA9, "credits_design_by", "Title credits: 'Original design and concept by'.")
DATA(0x9CCB, "credits_braybrook", "Title credits: 'Andrew Braybrook'.")
DATA(0x9CDF, "credits_programmed_by", "Title credits: 'Programmed by'.")
DATA(0x9CF0, "credits_robinson", "Title credits: 'Dominic Robinson'.")
DATA(0x9D04, "msg_hall_of_fame", "Message: 'Hall of Fame'.")
DATA(0x9D2C, "msg_land_now", "Message: 'LAND NOW'.")
DATA(0x9D48, "msg_three_mantas", "Message: ' 3 Mantas'.")
DATA(0x9D55, "msg_paused", "Message: ' Paused'.")
DATA(0x9D63, "msg_game_over", "Message: 'Game Over'.")
DATA(0x9D7E, "msg_enter_initials", "High-score prompt: 'enter your initials'.")
DATA(0x9DBB, "msg_dreadnought", "Message: 'Dreadnought'.")
DATA(0x9DCF, "msg_defences_penetrated", "Message: 'Defences Penetrated'.")
DATA(0x9DE2, "msg_destruct_sequence", "Message: 'Destruct Sequence Initiated'.")
DATA(0x9E05, "msg_wave_bonus", "Message: 'Wave destruction bonus'.")
DATA(0x9E29, "msg_dreadnought_bonus", "Message: 'Dreadnought destruction bonus'.")
DATA(0x9E52, "msg_options", "Message: 'Options'.")
DATA(0x9E62, "msg_prepare", "Message: 'Prepare'.")
DATA(0x9E7C, "msg_select_joystick", "Menu: 'Joystick'.")
DATA(0x9E88, "msg_select_keyboard", "Menu: 'Keyboard'.")
DATA(0xDD05, "wavetable1_element_names", "Wave name table 1: Zinc..Uridium (15 carriers).")
DATA(0xE500, "wavetable2_element_names", "Wave name table 2: Silicon..Uridium (15 carriers).")
DATA(0xFF59, "score_font_glyphs", "8x8 digit/letter bitmaps for the score panel.")


def main():
    # mechanical info from the recursive map: addr -> (callers, size, first)
    raw = open("uridium_funcref_raw.txt", encoding="utf-8").read().split("\n")
    mech = {}
    cur = None
    for ln in raw:
        m = re.match(r"FUNC \$([0-9A-F]{4})", ln)
        if m:
            cur = int(m.group(1), 16)
            mech[cur] = {"callers": [], "size": 0, "first": ""}
            continue
        if cur is None:
            continue
        mm = re.match(r"  CALLERS: (.*)", ln)
        if mm:
            mech[cur]["callers"] = [c for c in mm.group(1).split() if c.startswith("$")]
            continue
        mm = re.match(r"  SIZE   : (\d+) bytes", ln)
        if mm:
            mech[cur]["size"] = int(mm.group(1))
            continue
        mm = re.match(r"  FIRST  : (.*)", ln)
        if mm:
            mech[cur]["first"] = mm.group(1)

    out = []
    out.append("; URIDIUM - function reference (first-load 48K image, entry $F500)")
    out.append("; sources: recursive code map + linear sweep + dynamic trace + manual analysis")
    out.append("; per entry: CALLERS | IN | OUT | DESC")
    out.append("")

    out.append("=" * 74)
    out.append("PART 1 - DOCUMENTED FUNCTIONS AND ANCHORS")
    out.append("=" * 74)
    doc = 0
    for a in sorted(D):
        name, kind, inp, outp, desc = D[a]
        m = mech.get(a)
        out.append("")
        out.append("FUNC $%04X  %s" % (a, name))
        out.append("  KIND : " + kind)
        if m:
            cl = m["callers"]
            out.append("  CALLERS: " + (", ".join(cl[:6]) + (" (+%d more)" % (len(cl) - 6) if len(cl) > 6 else "") if cl else "(none - entered dynamically)"))
            out.append("  SIZE   : %d bytes mapped" % m["size"])
        out.append("  IN     : " + inp)
        out.append("  OUT    : " + outp)
        out.append("  DESC   : " + desc)
        doc += 1
    print("documented entries:", doc)

    # PART 2: recursive-map functions not already documented (in-image only)
    out.append("")
    out.append("=" * 74)
    out.append("PART 2 - ADDITIONAL FUNCTIONS FROM THE RECURSIVE CODE MAP")
    out.append("(mechanical entries - not yet analysed; $0000-$3FFF = ZX ROM)")
    out.append("=" * 74)
    extra = 0
    for a in sorted(mech):
        if a in D:
            continue
        m = mech[a]
        cl = m["callers"]
        cs = ", ".join(cl[:6]) + (" (+%d more)" % (len(cl) - 6) if len(cl) > 6 else "") if cl else "(entered dynamically)"
        region = "ROM" if a < 0x4000 else "RAM"
        out.append("")
        out.append("FUNC $%04X  (undocumented)  [%s]" % (a, region))
        out.append("  CALLERS: " + cs)
        out.append("  SIZE   : %d bytes mapped" % m["size"])
        out.append("  FIRST  : " + m["first"])
        extra += 1
    print("additional entries:", extra)

    open("uridium_function_reference.txt", "w", encoding="utf-8").write("\n".join(out))


if __name__ == "__main__":
    main()
